### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by sebasguts** [homalg-project/homalg_project#114]
<a href="https://github.com/sebastianpos"><img src="https://avatars.githubusercontent.com/u/2869916?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sebastianpos](https://github.com/sebastianpos)**
_Monday Oct 28, 2013 at 13:05 GMT_
_Originally opened as https://github.com/homalg-project/GradedModules/issues/17_

---

BettiTableOverCoeffcientsRing

**Comment by fingolfin** [comment]
This issue is still present (and seems rather trivial to fix, no?)

**Comment by mohamed-barakat** [comment]
There were a couple of other places outside of this repository which needed to be first found then adapted.
