### ISSUE TITLE
Error in README / missing tests

### ISSUE THREAD

**Issue by sebasguts** [homalg-project/homalg_project#129]
<a href="https://github.com/fingolfin"><img src="https://avatars.githubusercontent.com/u/241512?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [fingolfin](https://github.com/fingolfin)**
_Sunday Oct 05, 2014 at 21:05 GMT_
_Originally opened as https://github.com/homalg-project/4ti2Interface/issues/1_

---

The README says to test 4ti2Interface, one should do

```
ReadPackage( "4ti2Interface", "maketest.g" );
```

but this always fails, because there is no maketest.g

**Comment by mohamed-barakat** [comment]
Fixed by 05c7402.
