### ISSUE TITLE
Tension between RelationsOfModule and MatrixOfRelations

### ISSUE THREAD

**Issue by HereAround** [homalg-project/homalg_project#133]
Given a (f.p.) graded module M (e.g. the Coxring of a toric variety considered as module), one can consider RelationsOfModule( M ) and MatrixOfRelations( M ). It so happens that:
(_) HomalgRing( RelationsOfModule( M ) ) -> a NON graded ring
(_) HomalgRing( MatrixOfRelations( M ) ) -> a graded ring
-> Tension?

**Comment by mohamed-barakat** [comment]
This will probably disappear after rebasing homalg on CAP :)
