### ISSUE TITLE
RelationsOfModule vs. MatrixOfRelations for HomalgModuleElement

### ISSUE THREAD

**Issue by HereAround** [homalg-project/homalg_project#134]
Suppose that graded modules satisfied the filter "IsFinitelyPresentedModuleRep", so that the method HomalgModuleElement from the module package could be applied. Then for a pair (m, M) of a (f.p.) graded S-module M and a HomalgMatrix m with entries from S one can apply HomalgModuleElement. I optain the error "the two matrices are not defined over identically the same ring".

This seems related to the tension of "RelationsOfModule" and "MatrixOfRelations", namely the above error is triggered by line 293 in HomalgMap.gi which in turn results from line 286 which say

"rel := RelationsOfModule( Range( phi ) )" (-> defined over NON-graded ring)

Maybe one should replace this line by

"rel := MatrixOfRelations( Range( phi ) )"?

**Comment by mohamed-barakat** [comment]
Is this still relevant?

**Comment by HereAround** [comment]
No longer relevant to my knowledge. I close it.
