### ISSUE TITLE
EntriesOfHomalgMatrix

### ISSUE THREAD

**Issue by HereAround** [homalg-project/homalg_project#137]
m := HomalgMatrix( [[-1],[0]], HOMALG_MATRICES.ZZ );

I would have expected that "EntriesOfHomalgMatrix( m )" is a list of lists that describes the matrix m. In the above case this should thus be [[-1],[0}]. Still the output of gap is [-1,0].

**Comment by mohamed-barakat** [comment]
Simply use
```
EntriesOfHomalgMatrixAsListList( m );
```
