### ISSUE TITLE
Raygenerators of cone

### ISSUE THREAD

**Issue by HereAround** [homalg-project/homalg_project#139]
Why is the following happening?

LoadPackage( "Convex" );
C := Cone( [[1,1,1],[0,1,0],[-1,-1,-1],[0,-1,0]] )

So C is the vector space spanned by [1,1,1] and [0,1,0]. Now ask for ray generators of this cone.

RayGenerators( C );

This returns [ [ 1, 1, 1 ], [ 0, 0, 0 ], [ -1, -1, -1 ], [ 0, 0, 0 ] ] which is clearly incorrect.

**Comment by sebasguts** [comment]
This is caused by some change in the output of polymake in the recent version.

**Comment by mohamed-barakat** [comment]
This works with `NConvex`:

```gap
gap> LoadPackage( "NConvex" );
true
gap> C := Cone( [[1,1,1],[0,1,0],[-1,-1,-1],[0,-1,0]] );
<A cone in |R^3>
gap> RayGenerators( C );
[ [ -1, -1, -1 ], [ 0, -1, 0 ], [ 0, 1, 0 ], [ 1, 1, 1 ] ]
```
