### ISSUE TITLE
IsMorphism for multigraded modules

### ISSUE THREAD

**Issue by HereAround** [homalg-project/homalg_project#140]
Why is the following?

LoadPackage( "ToricVarieties" );
P1 := ProjectiveSpace( 1 );
P1xP1 := P1*P1;
ByASmallerPresentation( ClassGroup( P1xP1 ) );
M := 1 \* CoxRing( P1xP1 );
iota := EmbeddingInSuperObject( IrrelevantIdeal( P1xP1 ) );
IsIsomorphism( GradedHom( iota, M ) );

**Comment by sebasguts** [comment]
I think GradedHom for rings with other gradings than the standard Z grading is not implemented yet.

**Comment by HereAround** [comment]
It seems this issues is already caused by the embedding iota. Try for example:

IsMorphism( iota )

From this I get the following error:

Error, Record: '<rec>.MultiWeightedDegreesOfEntries' must have an assigned value in
  return RP!.MultiWeightedDegreesOfEntries( r, weights, R ); called from 
degree_help_function( mat ) called from
DegreesOfEntriesFunction( S )( C ) called from
DegreesOfEntries( UnderlyingMatrixOverNonGradedRing( C ), HomalgRing( C ) ) called from
DegreesOfEntries( MatrixOfMap( phi ) ) called from
<function "unknown">( <arguments> )
 called from read-eval loop at line 2 of *stdin*
you can 'return;' after assigning a value

This in turn seems to originate form the fact that the Cox Ring of P1 x P1 does not know the opperation "MultiWeightedDegreesOfEntries", which is confirmed from

homalgTable( CoxRing( P1xP1 ) )!.MultiWeightedDegreesOfEntries;

The above error can then be tracked to [GradedRingForHomalg/gap/Tools.gi, line 198]. Note also that

IsBound( GradedRingTableForSingularTools!.MultiWeightedDegreesOfEntries );

returns false.

**Comment by mohamed-barakat** [comment]
1. Implement `MultiWeightedDegreesOfEntries' for multi-graded rings.
2. Check why this correctly constructed morphism didn't know it is one.

Hotfix for 2. and then 1.:
SetIsMorphism( ..., true );
