### ISSUE TITLE
Loading GaussForHomalg from GaussForHomalg?

### ISSUE THREAD

**Issue by alex-konovalov** [homalg-project/homalg_project#147]
I can see the following warning in GAP regression tests:

```
#I  GaussForHomalg: Do not call `LoadPackage( "gaussforhomalg", ... )' in the package file
#I                  .....pkg/GaussForHomalg/gap/GaussRationals.gi,
#I                  use `IsPackageMarkedForLoading' instead
```

Not only that the warning suggests to use `IsPackageMarkedForLoading` but it also not clear to me how to check if the package is loaded from the file belonging to that package. However, I can't see LoadPackage in `GaussForHomalg/gap/GaussRationals.gi`. What happens is that its last line calls `HomalgFieldOfRationals` from MatricesForHomalg, and that function has these lines:

```
    if LoadPackage( "GaussForHomalg" ) <> true then
        Error( "the package GaussForHomalg failed to load\n" );
    fi;
```

However, MatricesForHomalg has dependencies

```
  NeededOtherPackages := [
                   [ "ToolsForHomalg", ">= 2012.10.27" ],
                   [ "GAPDoc", ">= 1.0" ] ],
  SuggestedOtherPackages := [ ],
```

so `GaussForHomalg` is not even mentioned there.

It would be nice to untangle this properly.

**Comment by alex-konovalov** [comment]
ping? ;-)

**Comment by mohamed-barakat** [comment]
I really do not want `MatricesForHomalg` to load anything except `ToolsForHomalg`. We often have problems with `Gauss` and hence with `GaussForHomalg` like this issues/149. Furthermore, I want an explicit Error only when `HomalgFieldOfRationals` is used.

**Comment by sebasguts** [comment]
The problems with Gauss are gone now, I think, since it does not require compilation anymore. Maybe we can refactor that logic.

**Comment by mohamed-barakat** [comment]
@sebasguts: Could you please elaborate on this?

**Comment by sebasguts** [comment]
Gauss does not need any compilation anymore, so your argument having trouble with Gauss does not apply anymore. The right behaviour here would be to just make `GaussForHomalg` a required package for `MatricesForHomalg`. I do not see any problem in doing so.

**Comment by sebasguts** [comment]
Since the declarations in `GaussForHomalg` depend on `MatricesForHomalg`, we cannot simply make `MatricesForHomalg` require `GaussForHomalg`. There are two possible solutions:

* Move the constructors for `Z/nZ` and `Q` to `GaussForHomalg`
* Make a new package containing these constructors

I prefer the first.

**Comment by mohamed-barakat** [comment]
In principle, `GaussForHomalg` is just a wrapper von `Gauss` and should not include further functionality other than that. But probably you are right and we should go for 1.: The rings Q and Z/nZ implement their `homalgTable` entries using `Gauss` and `GaussForHomalg`.

**Comment by sebasguts** [comment]
There is one more thing to discuss in that regard maybe. Currently `HomalgFieldOfRationals` and `HomalgRingOfIntegers` are global functions. Should we move them to `GaussForHomalg` as whole functions or split them up?

**Comment by mohamed-barakat** [comment]
`HomalgRingOfIntegers` should by all means remain in `MatricesForHomalg` as it does not depend on `Gauss`/`GaussForHomalg`. `HomalgFieldOfRationals` could be safely moved `GaussForHomalg`.

**Comment by alex-konovalov** [comment]
I still can see this warning in GaussForHomalg-2019.06.01.

**Comment by mohamed-barakat** [comment]
Thank @alex-konovalov for opening the issue and thank @sebasguts for providing a solution and thanks @zickgraf for setting up the current Jenkins :)
