### ISSUE TITLE
Ray generators of fan

### ISSUE THREAD

**Issue by HereAround** [homalg-project/homalg_project#153]
Why is the following happening?

LoadPackage ("Convex" );
fan := Fan( 
                   [ [ 1, 0, 0, 0 ], [ -1, 0, 0, 0 ], [ 0, 1, 0, 0 ], [ 0, 0, 1, 0 ], [ -2, -1, -1, 0 ], [ 0, 0, 0, 1 ], 
                     [ -3, -1, -1, -1 ] ],
                  [ [ 1, 3, 4, 6 ], [ 1, 3, 4, 7 ], [ 1, 3, 5, 6 ], [ 1, 3, 5, 7 ], [ 1, 4, 5, 6 ], [ 1, 4, 5, 7 ], 
                    [ 2, 3, 4, 6  ], [ 2, 3, 4, 7 ], [ 2, 3, 6, 7 ], [ 2, 4, 6, 7 ], [ 3, 5, 6, 7 ], [ 4, 5, 6, 7 ] ]
);

Then RayGenerators( fan ) produces the following output:
[ [ 1, 0, 0, 0 ], [ 0, 1, 0, 0 ], [ 0, 0, 1, 0 ], [ 0, 0, 0, 1 ], [ -1, 0, 0, 0 ], [ -1, 0, 0, 0 ], [ -1, 0, 0, 0 ] ]

Note that [ -1,0,0,0] appears 3 times, whilst according to the input we should have [-1,0,0,0], [ -2,-1,-1,0] and [-3,-1,-1,-1]. Yet, since we are considering cones, only R_{\geq 0} linear combinations of the input_rays can be considered, so that the ray [-2,-1,-1,0] and [-3,-1,-1,-1] must not be 'absorbed' into the remaining generators.

Could this be caused by a change in the output of polymake? I am using polymake 2.13.1, polymake_interface 2015.11.06 and convex 2015.11.06.

Also, could a check of "IsDuplicateFree" for e.g. RayGenerators( fan) maybe prove useful to detect inconsistencies in the future?

Thank you very much!

**Comment by sebasguts** [comment]
This is due to some change in polymake that happened a while ago, converting from unnormalized to normalized output. I fixed a similiar issue here: 1a462b987afc1de347c51bac7afc I am going to fix this too, very soon.

**Comment by sebasguts** [comment]
This patch solves this issue. Hopefully this is not a problem in more places. Will check soon.

**Comment by HereAround** [comment]
Thank you very much for the rapid fix! Indeed solves this issue.
