### ISSUE TITLE
Bugs in SimplerEquivalentMatrix

### ISSUE THREAD

**Issue by HereAround** [homalg-project/homalg_project#161]
Hi there,

I have the feeling that there are at least 2 bugs in the function `SimplerEquivalentMatrix` in `MatricesForHomalg` (`Basic.gi`).

First off all, if I am not mistaken this function should accept one matrix `M` as input and compute a 'simpler' matrix `M2` from it. Optionally this function computes matrices `U`, `UI`, `V` and `VI` s.t. `M * V = UI * M2` and `U * M = M2 * VI`.
[ Aside: Could this or something similar be added to the code as description of this function? Right now no description is available and hence the overall functionality is unclear - think of interchanging the roles of `U` and `V` for example. ]

Now I looked at the following:
```
LoadPackage( "RingsForHomalg" );
R := HomalgFieldOfRationalsInSingular();
M := HomalgMatrix( [[ 1,2,3 ],  [ 4,5,6 ]], R );
U := HomalgVoidMatrix( R );
UI := HomalgVoidMatrix( R );
V := HomalgVoidMatrix( R );
VI := HomalgVoidMatrix( R );
```
and handed this input to 'SimplerEquivalentMatrix'. Depending on which of the matrices U,UI,V and VI the function was asked to compute I obtained varying output as follows:
1. `SimplerEquivalentMatrix( M );`   ->  M2 = HomalgMatrix( [[ 1,0,0 ],  [ 0,1,0 ]] )
2. `SimplerEquivalentMatrix( M, V );`   -> M2 = 0 x 1 matrix, V = [[ 1 ], [ -2 ], [ 1 ]]
3. `SimplerEquivalentMatrix( M, VI, "" );`   -> M2 = 0 x 1 matrix, VI = [[0,0,1]]
4. `SimplerEquivalentMatrix( M, U, UI, "", "", "" );`   -> M2 = 0 x 1 matrix, U = 0 x 2 and UI = 2 x 0
5. `SimplerEquivalentMatrix( M, V, VI, "", "" );`   -> M2 = 0 x 1 matrix, V = [[ 1 ], [ -2 ], [ 1 ]] and 
                                                                                                         VI = [[ 0,0,1]]
6. `SimplerEquivalentMatrix( M, UI, VI, "" );`
   -> Causes an error because line 947 of Basic.gi wants to use arg[ 5 ]. However for this input only 4 
       arguments are available.
   -> Fixing this causes yet another error in the function 'Best basis' (just above 
       SimplerEquivalentMatrix), which I have not yet investigated further...
7. `SimplerEquivalentMatrix( M, U, V, UI, VI );` gives
   m2 = [[1,0,0],[0,1,0]], U = [[ 1, 0 ], [ 4/3, -1/3]], UI = [[ 1,0 ], [ 4,-3]], V = [[ 1,-2,1 ], [ 0,1,-2],[0,0,1]]
   VI = [[ 1,2,3 ], [0,1,2], [0,0,1]]
8. `SimplerEquivalentMatrix( M, U, V );` 
   -> does not even seem to terminate - I waited for about half an hour.

So overall
(_) There are (at least) 2 bugs in this function - see 6. and 8. above.
(_) Is it a feature or a bug that 2.-5. produce different `M2` (with different `U`,`UI`...) than 1. and 7. do?

**Comment by mohamed-barakat** [comment]
This procedure is module-theoretic and *not* matrix-theoretic. The behaviour you expect the procedure to comply to is not what this procedure is meant to do. Maybe you are mislead by the atypical/legacy use in 1, 6, 7, 8 which preserves the form of the matrix. The procedure is effectively only used in the scenarios 2, 3, 4, and 5.

Here is the correct explanation in a suggestive language:

The following are isomorphisms of modules:
row-coker(M) --(V)--> row-coker(M2)
row-coker(M2) --(VI)--> row-coker(M)
col-coker(M) --(U)--> col-coker(M2)
col-coker(M2) --(UI)--> col-coker(M)

**Comment by mohamed-barakat** [comment]
I'll adopt the fix you suggest for 6. Thanks 👍

**Comment by mohamed-barakat** [comment]
The problem in 8 is specific is a bug in the Singular interface in `RingsForHomalg`. Will upload a commit which fixes it.
