### ISSUE TITLE
Update prevents loading of package 'homalg' (and all packages based on it)

### ISSUE THREAD

**Issue by HereAround** [homalg-project/homalg_project#167]
With the updates starting from November 14, the package 'homalg' (and as a consequence GradedModules, Modules...) cannot be loaded any more. This happens both on my Laptop but also e.g. on emil in Aachen. LoadPackage( "homalg" ); leads to the following error message:

Error, BIND_GLOBAL: variable `Set' must be unbound called from
BIND_GLOBAL( name, value ); at /opt/gap/gap4r8p5/lib/global.gi:232 called from
BindGlobal( nname, SETTER_FILTER( attr ) 
 ); at /opt/gap/gap4r8p5/local/pkg/homalg_project/ToolsForHomalg/gap/ToolsForHomalg.gi:1363 called from
<function "DeclareAttributeWithCustomGetter">( <arguments> )
 called from read-eval loop at line 305 of /opt/gap/gap4r8p5/local/pkg/homalg_project/homalg/gap/HomalgMorphism.gd
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue

With the commit 8ba25ffb439cf1a7e7c168f02233f8f352c00256 the problem does not occure.

**Comment by mohamed-barakat** [comment]
I unfortunately keep getting PR on homalg-project although I keep begging people to send me their PR on mohamed-barakat. I know the problem, I'll fix it.
