### ISSUE TITLE
Examples for ToricVarieties don't work

### ISSUE THREAD

**Issue by fingolfin** [homalg-project/homalg_project#168]
I am trying to replicate the examples in http://www.gap-system.org/Manuals/pkg/ToricVarieties/doc/chap5.html#X8068F91F7C001DE7 using the master branch of homalg_project, but this fails.

First off, defining the cone gives a slightly different output; but more importantly, `CoordinateRing` produces an error:
```
gap> C:=Cone( [[1,0,0],[0,1,0],[0,0,1]] );
<A pointed cone in |R^3>
gap> C3:=ToricVariety(C);
<An affine normal toric variety of dimension 3>
gap> Dimension(C3);
3
gap> IsOrbifold(C3);
true
gap> IsSmooth(C3);
true
gap> CoordinateRingOfTorus(C3,"x");
Q[x1,x1_,x2,x2_,x3,x3_]/( x1*x1_-1, x2*x2_-1, x3*x3_-1 )
gap> CoordinateRing(C3,"x");
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `DualCone' on 1 arguments at /Users/mhorn/Projekte/GAP/gap.github/lib/methsel2.g:241 called from
DualCone( ConeOfVariety( variety )
 ) at /Users/mhorn/Projekte/GAP/repos/pkg/homalg_project/ToricVarieties/gap/AffineToricVarieties.gi:165 called from
CoordinateRing( variety, [ str ]
 ) at /Users/mhorn/Projekte/GAP/repos/pkg/homalg_project/ToricVarieties/gap/AffineToricVarieties.gi:136 called from
<function "unknown">( <arguments> )
 called from read-eval loop at *stdin*:17
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk>
```

**Comment by fingolfin** [comment]
I also get this with the latest version of the package bundle with GAp 4.8.6.

**Comment by fingolfin** [comment]
So the problem seems to be that there is no `DualCone` method for the cone I created; only `IsExternalConeRep` cones are supported. But how do I create such a cone?

I think `NormalizInterface` now supports everything needed for this, can this be used? Looking at the code, probably not...

**Comment by fingolfin** [comment]
And in a similar vein, I cannot reproduce the examples from Chapter 5 in the manual of the Convex package, see file:///Users/mhorn/Projekte/GAP/repos/pkg/homalg_project/Convex/doc/chap5_mj.html#X84BE1F7279A2C49C

This is a bit worse, because also the outputs that do work differ from what the example says:
```
gap> C := Cone([[1,2,3],[2,1,1],[1,0,0],[0,1,1]]);
<A pointed cone in |R^3>
gap> Length( RayGenerators( C ) );
4
gap> IsSmooth( C );
false
gap> Length( HilbertBasis( C ) );
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `HilbertBasis' on 1 arguments at /home/r/mhorn/gap/lib/methsel2.g:241 called from
<function "HANDLE_METHOD_NOT_FOUND">( <arguments> )
 called from read-eval loop at *stdin*:11
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk>
```

**Comment by sebasguts** [comment]
Thanks for pointing this out. Those errors occur when using `Convex` without `PolymakeInterface`. It has some fallback routines for some things, but it lacks certain functionality. I would like to make `PolymakeInterface` a needed package, not just an optional dependency, but this breaks the workflow of some people.

ATM, this code is in a stage of refactoring. We are currently rewriting `Convex` to use `NormalizInterface` as an alternative to `PolymakeInterface`, so it can choose between the two. Also, there will be the possibility to use `cdd`.

**Comment by mohamed-barakat** [comment]
After switching to your `NormalizInterface`, @sebasguts's `4ti2Interface`, and @kamalsalehs's `CddInterface` and `NConvex` the package `ToricVarieties` works again.

**Comment by sebasguts** [comment]
I would really like to create a new issue out of this. While the issue itself is solved, the problems I described in my comments remain, and are still an issue, since `Convex` does not really work without `PolymakeInterface`.

**Comment by mohamed-barakat** [comment]
You can reopen it if you like or create a new issue.

**Comment by sebasguts** [comment]
Well, I think a new one is more suitable, since the problem from this issue is solved.
