### ISSUE TITLE
Multiplication in HomalgRingOfIntegers(n) does not work, but in HomalgRingOfIntegers()/n does!

### ISSUE THREAD

**Issue by kamalsaleh** [homalg-project/homalg_project#170]
Z4 := HomalgRingOfIntegers( 4 );
#! Z/4Z
a := "3"/Z4;                    
#! 3
a^3=a;
#! false
a^3;
#! 27

Z4_ := HomalgRingOfIntegers( )/4;
#! Z/( 4 )
a := "3"/Z4_;                    
#! |[ 3 ]|
a^3=a;
#! true

**Comment by sebasguts** [comment]
it seems that for primes and prime powers the `RingElementConstructor`
is missing in the homalg ring.
