### ISSUE TITLE
Update this issue tracker: remove duplicates, close issues that have been long ago resolved?

### ISSUE THREAD

**Issue by fingolfin** [homalg-project/homalg_project#177]
This issue tracker seems to operate in write-only mode ;-), at least when it comes to older issues.

There are multiple duplicate issues, e.g.
* #1 vs #93 
* #2 vs #94 
* #3 vs #95 
* #4 vs #96 

Some issues seem like they have been resolved long ago, e.g. #7, #20, #72

Others have not enough information to know what they are about (and links they contain do no longer work), e.g. #88

**Comment by mohamed-barakat** [comment]
The duplication is probably an artifact of issue-migrations.

**Comment by fingolfin** [comment]
Yes, probably. 

Of course they are also still open :-). I really hope you guys will take some time at some point, to go through this issue tracker and close resolved or duplicate issues (and perhaps even address some of the other issues)... 

Some other trivial to resolve issues: #129, #130

**Comment by fingolfin** [comment]
@mohamed-barakat would be really nice if this was addressed at some point; right now, Homalg really gives the impression that a lot of it just isn't maintained anymore :-(
