### ISSUE TITLE
4ti2Interface to handle 4ti2 packages in debian

### ISSUE THREAD

**Issue by pedritomelenas** [homalg-project/homalg_project#187]
Debian and ubuntu now have a 4ti2 package, but all executables are installed with the prefix "4ti2-" (probably other linux distros). 

It would be great to be able to use this as an alternative to downloading/compiling/installing 4ti2 from source. 

Thank you,
Pedro

**Comment by kamalsaleh** [comment]
@sebasguts

**Comment by sebasguts** [comment]
This is fixed now and should be in the next homalg release
