### ISSUE TITLE
External conditions for 4ti2Interface empty

### ISSUE THREAD

**Issue by alex-konovalov** [homalg-project/homalg_project#189]
This should obviously specify 4ti2:

https://github.com/homalg-project/homalg_project/blob/3e2eaf46b4882a1750a1d85fd4ec7d8d45caa06f/4ti2Interface/PackageInfo.g#L65

**Comment by mohamed-barakat** [comment]
What is the format of this list?

**Comment by mohamed-barakat** [comment]
@alex-konovalov 

I see, it is just an info string

https://github.com/gap-packages/example/blob/master/PackageInfo.g#L331

Correct?

So would

`ExternalConditions := [ "https://4ti2.github.io/" ]`

be enough?

**Comment by alex-konovalov** [comment]
I suggest to use a pair `[text, URL]` instead 
```
  # needed external conditions (programs, operating system, ...)  provide 
  # just strings as text or
  # pairs [text, URL] where URL  provides further information
  # about that point.
  # (no automatic test will be done for this, do this in your 
  # 'AvailabilityTest' function below)
  # ExternalConditions := []
  ExternalConditions := []
```
then `ExternalConditions := [ ["4ti2", "https://4ti2.github.io/"] ]` will be rendered as [4ti2](https://4ti2.github.io/) on the GAP website.

**Comment by mohamed-barakat** [comment]
Thanks.
