### ISSUE TITLE
Ask Steve to support \[\]\:\= for general objects

### ISSUE THREAD

**Issue by sebasguts** [homalg-project/homalg_project#20]
<a href="https://github.com/mohamed-barakat"><img src="https://avatars.githubusercontent.com/u/871986?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mohamed-barakat](https://github.com/mohamed-barakat)**
_Saturday Mar 24, 2012 at 14:54 GMT_
_Originally opened as https://github.com/homalg-project/homalg/issues/20_

---

**Comment by fingolfin** [comment]
This is resolved, isn't it? @mohamed-barakat ?

**Comment by mohamed-barakat** [comment]
Yes, thanks :)
