### ISSUE TITLE
IsMorphism not implemented for IsHomalgRingMap

### ISSUE THREAD

**Issue by heiderich** [homalg-project/homalg_project#202]
The documentation for `RingMap` and `IsMorphism` suggests that one can test whether a ring map defined using `RingMap` is a ring morphism using `IsMorphism`. However this is not possible as the following example shows:

```
LoadPackage("Rings");
R := HomalgFieldOfRationalsInSingular()*"x";
phi := RingMap(["x"/R, R, R], R, R);
IsMorphism(phi);
```

**Comment by mohamed-barakat** [comment]
You are right, the documentation is misleading in promising an installed method for `IsMorphism` in general. Such methods need to dispatch depending on their sources and ranges. I'll remove the promise from the documentation.
