### ISSUE TITLE
Make latest ToricVarieties usable with the GAP distribution

### ISSUE THREAD

**Issue by alex-konovalov** [homalg-project/homalg_project#212]
After https://github.com/gap-system/gap-distribution/pull/67, I can now see new releases of three of homalg components. Two of them were picked up this morning, but this critical error prevents ToricVarieties from being imported:
```
* ToricVarieties - new version 2015.11.06 discovered!!!
  ============================================
  Getting new archives from 
  https://github.com/homalg-project/homalg_project/releases/download/ToricVari\
eties-2015.11.06/ToricVarieties-2015.11.06[ ".tar.gz", ".zip" ]
  unpacking ToricVarieties-2015.11.06.tar.gz
#E  component `WWWHome', if present, must be bound to a string started with ht\
tp://, https:// or ftp://
  ERROR (ToricVarieties): validation of the info file not successful! SKIPPING\
!!!
```
Also, this error should be fixed:
```
Error (Convex): could not get README file from
   http://homalg-project.github.io/homalg_project/Convex/README
```

**Comment by mohamed-barakat** [comment]
@alex-konovalov Please check it again and eventually close the issue manually:

@sebasguts fixed the issue with PR #214.

**Comment by sebasguts** [comment]
@alex-konovalov I now also pushed the `README` for Convex to the website. It might still cause a problem, as there was no release for Convex. Should I do a dummy release containing the `README`?

**Comment by alex-konovalov** [comment]
@sebasguts don't thinks that there is any urgency - the package has been imported and its testing is now underway. Would be nice to make a release before GAP 4.10 though.

**Comment by mohamed-barakat** [comment]
Great, thanks to both of you @alex-konovalov @sebasguts.

**Comment by alex-konovalov** [comment]
Of course this package will be unusable in the GAP distribution because of unsatisfied dependencies:
```
* ToricVarieties - new version 2018.10.12 discovered!!!
  ============================================
  Getting new archives from 
  https://github.com/homalg-project/homalg_project/releases/download/ToricVari\
eties-2018.10.12/ToricVarieties-2018.10.12[ ".tar.gz", ".zip" ]
  unpacking ToricVarieties-2018.10.12.tar.gz
  Validation of the info file successful!
  Package ToricVarieties 2018.10.12 from 12/10/2018 has dependencies:
  * NeededOtherPackages [ [ "NConvex", ">= 2017.01.01" ], 
  [ "GradedRingForHomalg", ">=2015.12.04" ], [ "Modules", ">=2016.01.20" ], 
  [ "GradedModules", ">=2015.12.04" ], [ "ToolsForHomalg", ">=2016.02.17" ], 
  [ "AutoDoc", ">=2016.02.16" ], [ "NormalizInterface", ">=0.9.8" ], 
  [ "CddInterface", ">= 2017.04.02" ], [ "4ti2Interface", ">= 2015.11.06" ] ]
  * GAP >=4.7
  * SuggestedOtherPackages [ [ "ToricIdeals", ">=2011.01.01" ] ]
```
because NConvex and CddInterface are not redistributed with GAP (as well as suggested package ToricIdeals).

What do you want me to do? Use ToricVarieties 2012.12.22 dated 22/12/2012 for now?

**Comment by mohamed-barakat** [comment]
Yes, indeed. We are internally using `NConvex` based on `NormalizInterface` and some other non deposited packages for `ToricVarieties` by now.

@sebasguts: I think we should make a release where `NConvex` is again replaced by `Convex` and postpone the shift to `NConvex` once meta-packages are supported.

**Comment by sebasguts** [comment]
@mohamed-barakat I would probably prefer to just merge Convex and NConvex at some point.

**Comment by mohamed-barakat** [comment]
@sebasguts: Yes, I agree, but till this point we should make a working release.

**Comment by sebasguts** [comment]
Indeed. I will try and fix this.

**Comment by alex-konovalov** [comment]
Ok - I will use the stable version of ToricVarieties for now: https://github.com/gap-system/gap-distribution/commit/181db0ca8c2570a40df35e648a59c99efe0ebd9f 

I have also updated the title of this issue.

**Comment by sebasguts** [comment]
So, from how I see this, all of those problems could be solved by reverting dfa896ca6734991fc30f960bceac2cb0bbbd767d . @mohamed-barakat  Are you okay with this?

**Comment by sebasguts** [comment]
@mohamed-barakat It is a merge commit that introduced a lot of changes, sure it does more than just adding dependencies. It also uses code from this dependencies. Just removing the unnecessary dependencies will not make the package loadable. If you want to extract everything that uses a new dependency and revert it to use the old dependency, i.e., PolymakeInterface, by hand, then go ahead.

**Comment by alex-konovalov** [comment]
Any progress @mohamed-barakat @sebasguts ?

**Comment by alex-konovalov** [comment]
PING @mohamed-barakat @sebasguts: as you can see in https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/PackageUpdate/Makefile GAP is enforced to use stable ToricVarieties, and as https://github.com/gap-system/gap/wiki/Package-updates-status reports, that is it's version from 2012. May we hope that a new release will happen in the foreseeable future (e.g. this or next week?)

**Comment by alex-konovalov** [comment]
Seen a bunch of package updates here today, but not of ToricVarieties. Hope none of these release relies on the ToricVarieties newer than its old 2012 release...

**Comment by mohamed-barakat** [comment]
@alex-konovalov, @sebasguts, @kamalsaleh, @HereAround 
In my opinion the best solution to make a new release for `ToricVarieties` is to deposit two new packages, namely `CddInterface` and `NConvex`, the latter depends on the already deposited `NormalizInterface`.

**Comment by alex-konovalov** [comment]
Certainly fine with me. Where can I see these packages at the moment?

**Comment by kamalsaleh** [comment]
Here you can find both of them: `https://github.com/homalg-project/NConvex` & `https://github.com/homalg-project/CddInterface`. I am of course ready to adjust anything when needed.

**Comment by alex-konovalov** [comment]
Thanks! Any reasons for non making the links clickable? You don't have to surround them with backticks.

**Comment by kamalsaleh** [comment]
This is probably because of the many issues and PR's with code recently. Anyway, they are clickable now ;)

**Comment by alex-konovalov** [comment]
I've picked up ToricVarieties 2019.04.02 but of course it's unusable without NConvex & CddInterface - to suggest to deposit them (i.e. add for the redistribution with GAP) please email to [GAP Support](https://www.gap-system.org/Contacts/People/supportgroup.html). 

@kamalsaleh, also you posted links to forks of these packages, rather than to main repos under your GitHub account - is that correct?

**Comment by kamalsaleh** [comment]
Thank you @alex-konovalov, I will contact the Gap support for depositing the packages very soon. Yes, the official releases are those in homalg-project account. It is then easier to maintain them when needed by the homalg-project members.

**Comment by alex-konovalov** [comment]
See https://github.com/gap-system/gap-distribution/issues/49 - ToricVarieties is now the oldest package in the GAP distribution because its newest version is unusable. It will be good to see this sorted in GAP 4.11.

**Comment by HereAround** [comment]
You are indeed right, we should try to resolve this. @mohamed-barakat - suggestions?

**Comment by alex-konovalov** [comment]
@HereAround for this, you need to submit NConvex and CddInterface for the redistribution with GAP.

**Comment by kamalsaleh** [comment]
@alex-konovalov  @HereAround  After cleaning the code and fixing some issues in the packages, I will contact tomorrow the Gap-Support for redistribution of CddInterface and NConvex with Gap.

**Comment by kamalsaleh** [comment]
@alex-konovalov I have already sent an email for distributing the packages the gap support team. wishes.

**Comment by alex-konovalov** [comment]
@kamalsaleh thanks, but when? It did not arrive yet.

**Comment by kamalsaleh** [comment]
At 18:00. Then I got this automatic reply:
Your mail to 'Support' with the subject _Distributing request of Gap packages: CddInterface & NConvex_
Is being held until the list moderator can review it for approval.

The reason it is being held:
The message headers matched a filter rule

Either the message will get posted to the list, or you will receive
notification of the moderator's decision.

**Comment by alex-konovalov** [comment]
@kamalsaleh thanks, it's now approved.

**Comment by HereAround** [comment]
@kamalsaleh - Thank you very much indeed. @alex-konovalov - if there is any other issue with the ToricVarieties package, then please let me know.

**Comment by alex-konovalov** [comment]
@HereAround this will be clear after those two package with be checked and picked up for the redistribution. Nothing to say until then.

**Comment by mohamed-barakat** [comment]
Can this issue be closed?

**Comment by alex-konovalov** [comment]
@mohamed-barakat not yet - sorry, that slipped from my attention for a while, as this was before the deadline I had on Aug 31st... @kamalsaleh there was a reply to you from @fingolfin in GAP Support on 29th August - are those suggestions already addressed? Anyhow, whenever they are or not yet, can you submit several PRs please:

- to https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/PackageUpdate/currentPackageInfoURLList to add two lines with URLs for PackageInfo.g files for both packages

- to https://github.com/gap-infra/gap-docker-pkg-tests-stable-4.11-devel/blob/master/.travis.yml and https://github.com/gap-infra/gap-docker-pkg-tests-master/blob/master/.travis.yml to add both packages to those Travis CI tests

**Comment by alex-konovalov** [comment]
@kamalsaleh very efficiently responded to all requests (thanks) and now both CddInterface & NConvex packages picked up for the redistribution. However, that makes ToricVarieties unusable again. It's old version required Convex, which can not be loaded simultaneously with NConvex. But the current ToricVarieties clashes with FinInG package. @kamalsaleh suggested a fix in https://github.com/homalg-project/homalg_project/pull/305 - a quick release would be very helpful.

**Comment by mohamed-barakat** [comment]
I just suggested a change to @kamalsaleh's latest request. When this issue is resolved I can make a new release of `ToricVarieties`.

**Comment by mohamed-barakat** [comment]
Thanks @kamalsaleh.

@alex-konovalov: I have just uploaded the latest `ToricVarieties`, could you please pick it up?

**Comment by alex-konovalov** [comment]
@mohamed-barakat as of 22 minutes ago:
```
Package: ToricVarieties
  No changes in PackageInfo.g file.
```
Could you please check why?

**Comment by alex-konovalov** [comment]
@mohamed-barakat I see it at https://github.com/homalg-project/homalg_project/releases/tag/ToricVarieties-2019.12.05 but not at https://homalg-project.github.io/homalg_project/ToricVarieties/ - who will be able to update the webpage?

**Comment by mohamed-barakat** [comment]
Sorry my mistake. Should be there now.

**Comment by alex-konovalov** [comment]
Thanks - picked up. Testing underway.

**Comment by mohamed-barakat** [comment]
Can this issue be closed?

**Comment by alex-konovalov** [comment]
yes, it can.
