### ISSUE TITLE
Issues with PolymakeIInterface

### ISSUE THREAD

**Issue by fingolfin** [homalg-project/homalg_project#215]
In `PackageInfo.g`:
* [ ] homepage URL for Thomas Baechler is not working (is he still in academia? If not, perhaps set `IsMaintainer := false`)
* [ ] homepage URL for @sebasguts is invalid (actually, I think this affects *all* your packages, and also many other people who so far have WWWHome URLs of the form `http://wwwb.math.rwth-aachen.de/~USERNAME`, so perhaps this should be fixed in one go for all homalg packages?
* [ ] package lists GAP 4.7 as minimal dependency; but you are using `RegisterPackageTNUM` which was only added in GAP 4.8, so you need to list at least that. And unless you are actually testing with GAP 4.8, I'd recommend to just use 4.9 as minimal version.
* [ ] polymake copyright is given as 1997-2012

In `README`:
* [ ] refers to tar.bz2 but the `PackageInfo.g` does not list that. Actually, I'd suggest to also drop `.zip` and only keep `.tar.gz` in `PackageInfo.g` and README; on gap-system, we automatically produce the other formats anyway.
* [ ] refers to @sebasguts email address in Aachen, is that still valid?
* [ ] perhaps give it a full overhaul, and also convert it to Markdown?

others:
* [ ] the build system is ... not good. Consider adopting the one we are using in e.g. `JuliaInterface`.
* [ ] consider replacing calls to `Exec` by `Process`, and adding error checking
* [ ] there are no tests, please consider adding a `TestFile` to `PackageInfo.g`. Of course we'll have to then disable those tests on the GAP travis for now, due to a lack of Polymake; but I hope this will change in the future
* [ ] why is there a `#define MORE_TESTS 1` hidden in `loadgap.h` -- is there in fact any reason one might ever want to disable those checks? Perhaps just get rid of it, and always enable them? Or at least change `#ifdef MORE_TESTS` everywhere to `#ifndef DISABLE_CHECKS`?
* [ ] it should be OK to simplify `loadgap.h` a lot, this should work (but I can't test it right now, as I have no polymake installed):
```C
#ifndef LOADGAP_H
#define LOADGAP_H

// include GAP headers
extern "C" {
#include <src/compiled.h>
}

#endif

#define MORE_TESTS 1
```

**Comment by mohamed-barakat** [comment]
We stopped supporting `PolymakeInterface` and `Convex` and they will not be deposited with GAP in the future. The part of their functionality we use in `ToricVarieties` is now covered by the deposited packages `NormalizeInterface`, `CddInterface`, and `NConvex`, the last two maintained by @kamalsaleh. Any future use of `polymake` will be through Polymake.jl which is a component of Oscar.

**Comment by mohamed-barakat** [comment]
Can this issue be closed?
