### ISSUE TITLE
PolyMakeInterface build doesn't report failures to BuildPackages.sh

### ISSUE THREAD

**Issue by RussWoodroofe** [homalg-project/homalg_project#221]
When running BuildPackages from GAP on a system without Polymake, PolymakeInterface (of course) fails to build.  However, it doesn't report its failure, and doesn't appear in fail.log.

This is a follow-on to GAP issue #2971, linked here:
https://github.com/gap-system/gap/issues/2971#issuecomment-441369073
@fingolfin had some helpful comments there about what was wrong, and how to fix it.

**Comment by RussWoodroofe** [comment]
This is still an issue in GAP 4.11.

**Comment by mohamed-barakat** [comment]
@sebasguts @alex-konovalov. I am in favor of removing `PolymakeInterface` from GAP's distribution. We do not maintain it anymore. Internally we switched to `NormalizInterface` and can now access `polymake` through OSCAR (`https://github.com/oscar-system/`).

**Comment by alex-konovalov** [comment]
@mohamed-barakat @sebasguts are there any of your packages that have `PolymakeInterface` in their dependencies?

**Comment by kamalsaleh** [comment]
`PolymakeInterface` is a suggested-other-package in the `Convex` package.

**Comment by mohamed-barakat** [comment]
Yes, `Convex` should also be dropped from `homalg_project`.

**Comment by mohamed-barakat** [comment]
@alex-konovalov: Please drop `PolymakeInterface` and `Convex` from the future GAP distribution. They are now replaced by `NormalizInterface` and `NConvex`.

**Comment by mohamed-barakat** [comment]
We stopped supporting `PolymakeInterface` and `Convex` and they will not be deposited with GAP in the future. The part of their functionality we use in `ToricVarieties` is now covered by the deposited packages `NormalizeInterface`, `CddInterface`, and `NConvex`, the last two maintained by @kamalsaleh. Any future use of `polymake` will be through `Polymake.jl` which is a component of `Oscar`.

**Comment by mohamed-barakat** [comment]
I will close this issue soon.

**Comment by alex-konovalov** [comment]
@mohamed-barakat have you checked that the action is done? Because I do not remember sseing this and https://www.gap-system.org/Packages/polymakeinterface.html is still there. If this is still OK, please submit an issue at https://github.com/gap-system/gap-distribution or even a PR to https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/PackageUpdate/currentPackageInfoURLList to withdraw the package.

**Comment by mohamed-barakat** [comment]
Thanks, I will make a PR.

I will then withdraw `PolymakeInterface` and `Convex`:

What about the two files

* `wininst/gap.nsi
* `wininst/wininst.g`

Do I need to modify them as well?

**Comment by alex-konovalov** [comment]
> I will then withdraw PolymakeInterface and Convex:

Only the 1st one (Convex already replaced by NConvex)

> What about the two files
>
> wininst/gap.nsi
> wininst/wininst.g
>
> Do I need to modify them as well?

Modify only `wininst/wininst.g` please. The other is autogenerated.
