### ISSUE TITLE
Toric varieties depends on order of rays/maximal cones...

### ISSUE THREAD

**Issue by HereAround** [homalg-project/homalg_project#225]
I found that ToricVarieties depends on the order of the rays/maximal cones - compare the original issue raised at the NConvex package:

https://github.com/kamalsaleh/NConvex/issues/8

A priori, no such dependency should exist (unless I am mistaken). Consequently, this needs to be investigated further.

**Comment by sebasguts** [comment]
The way polymake returned some data led to this dependency: The output of maximal cones in Polymake gives you an incidence matrix. I think I decided back then that convex should mirror this data structure transparently.

Because our tests are not really good, an order change can break them.

**Comment by mohamed-barakat** [comment]
@HereAround: What is the status of this issue? Is it by now obsolete?

**Comment by HereAround** [comment]
It is good to bare this in mind. Still - I think we can close this issue and leave things as they are.

**Comment by mohamed-barakat** [comment]
I will probably be sorting outputs uniquely when I come to clean up the packages within the coming months.
