### ISSUE TITLE
PolymakeInterface doesn't build with polymake 3.3

### ISSUE THREAD

**Issue by antonio-rojas** [homalg-project/homalg_project#228]
Building with polymake 3.3:
```
src/polymake_fan.cpp:96:20:` error: no match for ‘operator+=’ (operand types are ‘pm::Set<int, pm::operations::cmp>’ and ‘Int’ {aka ‘long int’})
incMatr[i] += INT_INTOBJ( numb ) - 1;
In file included from /usr/include/polymake/Set.h:20,
from /usr/include/polymake/next/IncidenceMatrix.h:26,
from /usr/include/polymake/IncidenceMatrix.h:20,
from src/polymake_data.h:8,
from src/polymake_fan.h:2,
from src/polymake_fan.cpp:1:
/usr/include/polymake/next/Set.h:450:4: note: candidate: ‘template<class Right> std::enable_if_t<pm::GenericMutableSet<TSet, E, Comparator>::is_compatible_set<Right>::value, typename pm::GenericSet<Set, E, Comparator>::top_type&> pm::GenericMutableSet<TSet, E, Comparator>::operator+=(const Right&) [with Right = Right; TSet = pm::Set<int, pm::operations::cmp>; E = int; Comparator = pm::operations::cmp]’
operator+= (const Right& x)
^~~~~~~~
```

**Comment by antonio-rojas** [comment]
Patch that fixes build for me:
https://git.archlinux.org/svntogit/community.git/tree/trunk/gap-polymake-3.3.patch?h=packages/gap&id=af3bf572a50f84f0596de8b1d991e9be16a9aa7e

**Comment by mohamed-barakat** [comment]
@sebasguts: What is the status of this?

**Comment by mohamed-barakat** [comment]
@sebasguts: Shall we discontinue the support for `PolymakeInterface` and refer users it via the new `JuliaInterface`?

**Comment by mohamed-barakat** [comment]
For the records: I will disable testing `PolymakeInterface` and `Convex`. We stopped supporting the two packages and they will not be deposited with `GAP` in the future. The part of their functionality we use in `ToricVarieties` is now covered by the deposited packages `NormalizeInterface`, `CddInterface`, and `NConvex`, the last two maintained by @kamalsaleh. Any future use of polymake will be through `Polymake.jl` which is a component of `Oscar`.

**Comment by mohamed-barakat** [comment]
I will close this issue.
