### ISSUE TITLE
DeclareSynonym ( "Reduce", DecideZero ) incompatible with QPA2

### ISSUE THREAD

**Issue by heiderich** [homalg-project/homalg_project#230]
The use of 

https://github.com/homalg-project/homalg_project/blob/e2f8e9f123a99267f3a88867ab28a813445d966d/Modules/gap/HomalgRelations.gd#L234-L235

 is incompatible with https://github.com/oysteins/QPA2 as illustrated in the following two situations:

## Situation 1

```
LoadPackage("QPA");
LoadPackage("Modules");
```

leads to

```
Error, BIND_GLOBAL: variable `Reduce' must be unbound
```

during the above mentioned `DeclareSynonym`.

## Situation 2

```
LoadPackage("Modules");
LoadPackage("QPA");
```

does not lead to errors, but allows to use `DecideZero` as a synonym for the operation `Reduce` declared in QPA2, which is maybe not wanted. In general it seems that the use of `DeclareSynonym` makes the initial name and the new one indistinguishable. Therefore I guess that it should be used with care, especially for generic names such as `Reduce`.

I see the following solutions:

* remove https://github.com/homalg-project/homalg_project/blob/e2f8e9f123a99267f3a88867ab28a813445d966d/Modules/gap/HomalgRelations.gd#L234-L235
* declare operations `Reduce` with the same filters as `DecideZero` and install methods for them that call `DecideZero`.

**Comment by mohamed-barakat** [comment]
I have already resolved this in my `devel` branch:

https://github.com/mohamed-barakat/homalg_project/commits/devel
