### ISSUE TITLE
Create a 1x0 matrix in Singular using a list of lists

### ISSUE THREAD

**Issue by heiderich** [homalg-project/homalg_project#232]
The following code creates a 1 x 0 matrix over the internal field of rationals:

```
Q := HomalgFieldOfRationals();
HomalgMatrix([[]], 1, 0, Q);

```
I would expect that the following code would create a matrix with one row and zero columns over the field of rationals in Singular:

```
LoadPackage("RingsForHomalg");
Q := HomalgFieldOfRationalsInSingular();
M := HomalgMatrix([[]], 1, 0, Q);
```

However an error occurs:

```
Error, the external CAS Singular (running with PID 5686) returned the following error:
   ? error occurred in or before STDIN line 1226: `matrix homalg_variable_5[1][0] = ;`
   ? expected matrix-expression. type 'help matrix;'
   ? last reserved name was `matrix`
```

Equally it would be nice if 

`HomalgMatrix([[]], Q);`

would also create the above mentionned matrix instead of throwing the same error.

**Comment by mohamed-barakat** [comment]
First of all empty matrices should be using `HomalgZeroMatrix`.

Second, `Singular` does not understand the listlist notation, this is why in the documentation of `HomalgMatrix` the string-list-notation
```
HomalgMatrix( "[a,b,c,...]", m, n, R )
```
is the recommended input style which works with all oracles.

**Comment by mohamed-barakat** [comment]
In fact, I can internally call `HomalgZeroMatrix` internally once one of the dimensions is zero.

**Comment by heiderich** [comment]
Let me explain my use case. I tried to avoid using strings as much as possible as in the following example:

```
LoadPackage("RingsForHomalg");
vars_string := "x,y";
R := HomalgFieldOfRationalsInSingular()*vars_string;
vars := Indeterminates(R);
HomalgMatrix([ vars ], Length(vars), 1, R);
```

This however fails with `vars_string := "";`as explained above.

> First of all empty matrices should be using `HomalgZeroMatrix`.

I was just hoping for a uniform way to construct matrices as in the above example, including the case of no columns.

> Second, `Singular` does not understand the listlist notation, this is why in the documentation of 
`HomalgMatrix` the string-list-notation

The above example working, I was hoping that homalg would handle this notation.

> In fact, I can internally call `HomalgZeroMatrix` internally once one of the dimensions is zero.

This was in fact my hope. @zickgraf had a similar (the same?) issue yesterday. It would probably lead to less code if this special case would be handled in `HomalgMatrix`.

**Comment by mohamed-barakat** [comment]
Please try

`HomalgMatrix( vars, Length(vars), 1, R);`

**Comment by heiderich** [comment]
This works. Thanks!

I still think it would be nice if this could be supported. Then probably something like

`M := HomalgMatrix([ List(vars, i -> vars) ], Length(vars), Length(vars), R);`

would also work generically.

**Comment by heiderich** [comment]
However I am not sure whether this actually should work in the case where `vars` is an empty list, as `[[]]` should describe a matrix with one row and no columns.

**Comment by mohamed-barakat** [comment]
The clean solution will be to ignore the first argument once one of the dimensions is zero.

**Comment by sebasguts** [comment]
@mohamed-barakat is right: The first argument should simply be ignored. Although we should still make it an `IsList`, so it can only be a string or a list, so we do not give people too much lever to do stupid things if we want to change something again.
