### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by fingolfin** [homalg-project/homalg_project#236]
Several of the packages in homalg_project are licensed under GPL 2, but not under "GPL 2 or later". From a legal point of view, this is a serious issue, as that means those packages should not be used together with packages that are licensed under GPL 3 -- such as the io package, which I understand is used quite a bit by parts of homalg.

Could you perhaps relicense those subpackages to allow for "GPL 2 or later"?

While at it, you could also add suitable `License` fields to the various `PackageInfo.g` files; and clarify the license of the `ToricVarieties` package by @sebasguts and @HereAround 

I could also provide a pull request doing all this (assuming `ToricVarieties` is also "GPL 2 or later"), but I don't want to waste time if that's not something you'd consider.

**Comment by mohamed-barakat** [comment]
Thank you very much for pointing this out. I agree and would be grateful for such a PR. Thanks Max.

**Comment by fingolfin** [comment]
Done in PR #239
