### ISSUE TITLE
BaseRing of a polynomial ring over the field of rationals

### ISSUE THREAD

**Issue by heiderich** [homalg-project/homalg_project#248]
According to the documentation of `BaseRing`

https://github.com/homalg-project/homalg_project/blob/b982aa17ce2bfff8f649666933f465acc06d22ab/MatricesForHomalg/gap/HomalgRing.gd#L1225 

I would expect the following to work:

```
LoadPackage("RingsForHomalg");
BaseRing( HomalgFieldOfRationalsInSingular()*"x" );
```

However it fails with "Error, no 1st choice method found for `BaseRing' on 1 arguments".

Note: There is already a (reference to an) issue concerning `BaseRing` (#35). However I am unable to access the original issue.

**Comment by mohamed-barakat** [comment]
Fixed with commit 3eb9379.
