### ISSUE TITLE
MatrixOfWeightsOfIndeterminates cannot be displayed

### ISSUE THREAD

**Issue by HereAround** [homalg-project/homalg_project#250]
LoadPackage( "GradedRing" );
Q := HomalgFieldOfRationalsInSingular();
S := GradedRing( Q * "x, y" );
SetWeightsOfIndeterminates( S, [ 1, 1 ] );
m := MatrixOfWeightsOfIndeterminates( S );
Display( m );

Error, the external CAS Singular (running with PID 13591) returned the following error:
   ? transpose(`list`) failed

I use b982aa17ce2bfff8f649666933f465acc06d22ab.

**Comment by mohamed-barakat** [comment]
I promised too much here. This is not a valid `IsHomalgMatrix` and is used internally as the wrapper of the external objects it points to. This why `Display` fails. I suggest to remove the documentation of `MatrixOfWeightsOfIndeterminates` as it promises too much an is not meant for the end user.

**Comment by HereAround** [comment]
Does https://github.com/homalg-project/homalg_project/pull/268 solve this issue?

**Comment by mohamed-barakat** [comment]
Yes :)
