### ISSUE TITLE
Discussion - how to extend NConvex/toric varieties

### ISSUE THREAD

**Issue by HereAround** [homalg-project/homalg_project#252]
In this issue, I would like to discuss extensions of ToricVarieties and also NConvex. Therefore, I would like to hear if and how this can become part of the homalg_project.

First of all, I provide two new interfaces (still undergoing development):
- https://github.com/HereAround/TopcomInterface
- https://github.com/HereAround/cohomCalgInterface

The former establishes an interface to the software Topcom (http://www.rambau.wm.uni-bayreuth.de/TOPCOM/). It is used for triangulations of polytopes. In particular, we can use this to triangulate a fan of a toric variety. By this I mean the following:

- Input: Ray generators
- Output: All fans (with specific properties) whose ray generators match whose provided as input.

A (currently very very basic) implementation of this method is provided in my package 
https://github.com/HereAround/TriangulationsAndBlowupsForToricVarieties. The latter also implements the blow-up of a toric variety via a star subdivision of the fan (cf. Cox-Little-Schenk Def. 3.3.17).

All of this, i.e. triangulations of polytopes/fans and blowups via star subdivision of fans are from my point of view well-suited to extend NConvex. So in particular this agrees with your suggestion @mohamed-barakat in https://github.com/homalg-project/homalg_project/issues/212. 

@kamalsaleh and @sebasguts , I would like to hear what you think about such an extension of NConvex. Also, suggestions to improve my TopcomInterface (https://github.com/HereAround/TopcomInterface) are highly appreciated.

Regarding the second interface - https://github.com/HereAround/cohomCalgInterface. This establishes an interface to the software cohomCalg (c.f. https://github.com/BenjaminJurke/cohomCalg) which is used to compute sheaf cohomologies of line bundles on toric varieties. 

I use this in my package https://github.com/HereAround/SheafCohomologyOnToricVarieties. Among others I compute vanishing sets by use of this software. By a slight extension it is also possible to compute Hodge-Diamonds of (many) complete intersections in toric varieties. This is not yet supported by my packages, but I plan to provide this functionality soonish. 

Finally, my package https://github.com/HereAround/SheafCohomologyOnToricVarieties contains code to compute intersection numbers, Nef and Mori cones,... in toric varieties. And of course, this package also contains an implementation of my algorithm to compute cohomologies of coherent sheaves. The latter I describe in https://arxiv.org/pdf/1802.08860.pdf appendix B.

I believe we should essentially debate two different topics:
1. Extension of NConvex:
For example develop my topcom-Interface further and thereby extend NConvex to support triangulations of fans (and, while we are at it also blowups with star subdivisions).
2. Extension of ToricVarieties:
One way would be to simply extend the toric varieties package with (part of) the above functionality, once the interfaces run according to our wishes and needs. Alternatively, one could also think of setting up a "ToricVarietiesExtension" package, which can eventually be merged with the ToricVarieties package.
Alternatively, a more involved, but maybe more advantageous approach on the long run, would be to first set up the "CAPCategoryOfToricSchemes" (and maybe also a "CAPCategoryOfAffineSchemes"), and then extend this package with the above-mentioned functionality. Such a package would then (probably?) be part of the CAP_project...

I would certainly enjoy making the above available within the homalg_project or CAP_project. Suggestions and feedback are highly appreciated. In particular I would love to hear from @mohamed-barakat, @sebasguts, @sebastianpos  and @kamalsaleh what you think about such extensions. Would you be interested in making (part of the above) part of the homalg_project and if so how?

**Comment by mohamed-barakat** [comment]
I support extending NConvex as you suggest.

Regarding your suggestion about a new CAP-based package supporting varieties. Please have a look at my new package ZariskiFrames. There I support affine and projective varieties. A basic support for toric varieties can be added easly by the design of the package.

**Comment by HereAround** [comment]
I will then discuss the steps regarding the extension of NConvex with @kamalsaleh . Also, thanks for pointing me to your ZariskiFrames package. I will have a detailed look at it during the next few days. Afterwards, I will comment on your suggestion.

What do you think of the cohomCalg interface? As mentioned, it allows to compute vanishing sets (i.e. the collection of all line bundles for which a sheaf cohomology h^i vanishes) and also the Hodge diamonds for many complete intersections in toric spaces within seconds. To my understanding, this is a neat extension of the functionality. However, it also requires and additional dependency for the toric varieties package...

Finally, I remember that we agreed a few years ago not to migrate the Nef- and Moricone computations as well as the basic intersection computations (both contained in my sheaf cohomology package) into ToricVarieties. However, I do no longer recall the reasoning. 

Is this still the case, and if so, what was the reasoning again? If not, then I can easily provide PRs for the Nef- and Moricones. However, with regards to the intersection theory, I would aim higher and try to cover the Chow ring of toric varieties.

**Comment by HereAround** [comment]
Update:
- I have placed a preliminary version of the cohomCalg interface here:
https://github.com/HereAround/SheafCohomologyOnToricVarieties
- SheafCohomologyOnToricVarieties has been completely restructured. In particular, it now uses the FpGradedModules that I implemented with @sebastianpos in FreydCategories.
- Currently, SheafCohomologyOnToricVarieties contains a lot of methods that can be collected in individual packages (e.g. truncations of f.p. graded modules). I will turn to this shortly.
- Likewise, SheafCohomologyOnToricVarieties contains methods to turn an FpGradedModule into an "old" gap-module (i.e. one that is implemented in the GradedModules package). I plan to move also these commands into an individual package soon (e.g. "ToolsForFPGradedModules"). @mohamed-barakat , you mentioned that there exist methods for the conversion of the CAP f.p. graded-modules implemented by @sebasguts and the ones implemented in GradedModules. Could you provide a pointer to this code, so that I can adjust my methods accordingly?
- Also, eventually there should exist a conversion between the f.p. graded modules implemented in FreydCategories and the ones by @sebasguts.

**Comment by mohamed-barakat** [comment]
> * Likewise, SheafCohomologyOnToricVarieties contains methods to turn an FpGradedModule into an "old" gap-module (i.e. one that is implemented in the GradedModules package). I plan to move also these commands into an individual package soon (e.g. "ToolsForFPGradedModules"). @mohamed-barakat , you mentioned that there exist methods for the conversion of the CAP f.p. graded-modules implemented by @sebasguts and the ones implemented in GradedModules. Could you provide a pointer to this code, so that I can adjust my methods accordingly?

@kamalsaleh wrote some code to convert between homalg <-> CAP (graded) modules.

**Comment by mohamed-barakat** [comment]
> * I have placed a preliminary version of the cohomCalg interface here:
>   https://github.com/HereAround/SheafCohomologyOnToricVarieties
> * SheafCohomologyOnToricVarieties has been completely restructured. In particular, it now uses the FpGradedModules that I implemented with @sebastianpos in FreydCategories.

I made you an admin for https://github.com/homalg-project/SheafCohomologyOnToricVarieties. If you like you can give me lower access rights and use this URL as your main one.

**Comment by HereAround** [comment]
Thank you very much indeed Mohamed! I will indeed use https://github.com/homalg-project/SheafCohomologyOnToricVarieties for the future developments/issues etc. What rights did you have in mind/are you currently in need of?

@kamalsaleh - Could you point me to your code that converts homalg <-> CAP (graded) modules? I would like to extend this interface so that also conversion into/from the graded modules encoded in the FreydCategories-package are possible. Thanks! (Maybe, we should open a separate issue/discussion to address this?)

**Comment by mohamed-barakat** [comment]
I suggest the following:

1. I can delete the forks of all your packages on homalg-project
2. You can transfer the rights from HereAround to homalg-project
3. I can grant you admin rights to your repositories

What do you think?

**Comment by HereAround** [comment]
Sounds good. Let's do it.

**Comment by kamalsaleh** [comment]
@HereAround  You can find the interface here https://github.com/kamalsaleh/BBGG/blob/master/gap/InterfaceWithHomalg.gi

**Comment by HereAround** [comment]
Thanks. I will look into this.

**Comment by mohamed-barakat** [comment]
> Sounds good. Let's do it.

Excellent. I now deleted all your forked packages on `homalg-project`. You can now transfer them and I can then grant you admin rights.

**Comment by HereAround** [comment]
I will transfer the following packages to homalg-project:

- https://github.com/HereAround/CAPCategoryOfProjectiveGradedModules
- https://github.com/HereAround/CAPPresentationCategory
- https://github.com/HereAround/PresentationsByProjectiveGradedModules
- https://github.com/HereAround/TruncationsOfPresentationsByProjectiveGradedModules
- https://github.com/HereAround/TopcomInterface
- https://github.com/HereAround/SheafCohomologyOnToricVarieties

However, for this I need the right to create public repositories in homalg_project (c.f.
https://help.github.com/en/github/administering-a-repository/transferring-a-repository, 2nd point in section "about repository transfers"). Thank you!

**Comment by kamalsaleh** [comment]
Alternative:
@mohamed-barakat removes the forks from his github,
`homalg` forks the packages again.
Martin removes the packages,
Martin forks the packages again from `homalg`.

**Comment by alex-konovalov** [comment]
Except if you started to create issues in forks and have some to rescue first...

**Comment by mohamed-barakat** [comment]
I have now updated all packages on my branch. If we follow Kamal's suggestion please double-check:

1. I am the only one who forked from you.
2. I have the latest branches
3. I have all branches
4. There are no issues or PR on your branches.

**Comment by HereAround** [comment]
Unfortunately, only 4 is satisfied:

As for 1, https://github.com/HereAround/SheafCohomologyOnToricVarieties was also forked by @fingolfin . 

As for 2,3 @mohamed-barakat you seem to have the lastest master branch. But you are missing some of the other branches.

Alternatively and maybe simpler - could you grant me the rights to create public repositories in the homalg-project temporarily. Hopefully I can then easily transfer the rights on my packages to homalg-project. Subsequently, you can again revoke my right to create public repositories and grant me admin rights for the packages.

**Comment by alex-konovalov** [comment]
The problem of dining philosophers picking forks becomes a problem of programming philosophers removing forks :)

**Comment by mohamed-barakat** [comment]
I sent you a membership request.

**Comment by HereAround** [comment]
@mohamed-barakat Thank you very much indeed. I accepted that invitation and joined the homalg-project. 

Still, when I try to transfer the rights to the homalg-project, github reacts with "You don’t have the permission to create public repositories on homalg-project".

**Comment by mohamed-barakat** [comment]
Please try again now and tell me when you finish.

**Comment by HereAround** [comment]
@mohamed-barakat Thanks! The rights/packages have been transferred to the homalg-project successfully.

**Comment by mohamed-barakat** [comment]
I thank you. I now granted you admin rights for all six repositories.

**Comment by mohamed-barakat** [comment]
I am planning to detach the package `ToricVarieties` from the `homalg_project` repository and add to it the capabilities of `ToricSheaves` which relies on

* Serre's quotient construction (implemented `GeneralizedMorphismsForCAP`)
* computation of generators of toric ideals (needs `4ti2Interface` or `GradedRingForHomalg` `v2020.04.25`)
* computation of lattice points of lattice polytopes (needs `NormalizInterface`, `NConvex`)

**Comment by HereAround** [comment]
Thank you for the update.

In principle, I think it is a good idea to think of a better place for the ToricVarieties packages. However, I am not entirely certain if ToricSheaves is the right place for this.

First, I think this package needs improvement. Namely, the last time I looked at this Package, it still depended on PolymakeInterface. Maybe you changed this in the meantime? Secondly, many of the functions in this package were not properly declared, but only implemented as global functions. Also, the documentation is to my understanding far from complete.

Secondly, I have been willing to extend my SheafCohomologiesPackages to use Serre quotient for a long time. Earlier this year, I have finally extended TruncationsOfFPGradedModules to support the necessary 'localized truncations', and am therefore not able to construct Serre quotient based on the FPGradedModules implemented via FreydCategories. All of this is based on a combination of NConvex, CddInterface and 4ti2. Also, it fixes many of the above-mentioned shortcomming. See e.g. https://github.com/homalg-project/SheafCohomologyOnToricVarieties/tree/master/TruncationsOfFPGradedModules) for more details.

Thirdly, based on the above, a cousin of ToricSheaves (but based on TruncationsOfFPGradedModules and adapted for the FPGradedModules in FreydCategories) is the package https://github.com/homalg-project/SheafCohomologyOnToricVarieties/tree/master/CoherentSheavesOnToricVarieties.

That all said - it seems more natural to me to make ToricVarieties and ToricSheaves part of SheafCohomologies. In particular, since ToricVarieties is (at least not yet) a CAP-package. What do you think?

**Comment by mohamed-barakat** [comment]
Dear Martin, I agree. The code quality of `ToricSheaves` is considerably lower than other package in the CAP project.

However:

1. It now indeed uses `NConves` and `CddInterface`: See https://github.com/homalg-project/CAP_project/pull/515.
2. It can compute the restriction functors to the affine toric charts and this code should be refactored and probably transferred somewhere else, where it could be maintained and enhanced.

I suggest splitting `ToricVarieties` from the `homalg_project` repository so that you can include it as a package in your `SheafCohomologiesOnToricVarieties` package. I also suggest refactoring the above-mentioned code of `ToricSheaves` in one of your packages. I hope this is OK for @sebasguts and @sebastianpos. If there is a consensus you Martin and I can start doing this in June.

We have to do the subtree splitting and mering properly for [`homalg_stats`](https://github.com/homalg-project/homalg_stats) to work nicely. I will forward you an email form @zickgraf.

**Comment by HereAround** [comment]
Dear Mohamed,

thank you for the update, also on the subsplitting problem. I will bare this in mind.

Regarding your proposal - I fully agree to this.

Hence, let us hear from @sebasguts and @sebastianpos. If both agree, we can indeed start with the necessary steps in June.

**Comment by sebastianpos** [comment]
I'm okay with splitting `ToricSheaves` from the `homalg_project`.
Since @sebasguts transfered the right to make such decisions to me, it suffices that I give my okay.

For me, the most important part is that we should have a hom structure for the category of graded rows in the future (as part of the `FreydCategoriesForCAP` package), which essentially is @sebasguts  algorithm for computing graded parts as S_0 modules. Also, I would prefer if that hom structure does not rely on too many additional external systems.

**Comment by kamalsaleh** [comment]
I totally agree with you, it would be very nice to have hom structure over the category of graded rows. At the moment I have implemented the easy case, namely, when the ring is the free polynomial ring with finite number of monomials in each degree see [DerivedCategories/gap/ToolsForFreydCategories.gi](https://github.com/homalg-project/DerivedCategories/blob/master/gap/ToolsForFreydCategories.gi) . But hom structure for the general case would be a huge improvement.

**Comment by mohamed-barakat** [comment]
Just for clarification: `ToricVarieties` is part of the repository `homalg_project`. `ToricSheaves` is part of the repository `CAP_project`. I suggest

* splitting `ToricVarieties` and moving it to Martin's repository `SheafCohomologiesOnToricVarieties`
* either splitting or refactoring the code of `ToricSheaves` in `SheafCohomologiesOnToricVarieties`.

**Comment by mohamed-barakat** [comment]
Can this issue be closed now?

**Comment by HereAround** [comment]
Yes. This can be closed now. Any new developments in this direction will be in https://github.com/homalg-project/ToricVarieties_project.
