### ISSUE TITLE
Missing dependency on `utils`

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/homalg_project#254]
5b1020ba4d1959963531c95058039c0b1b7350ce uses the operation `RandomCombination`. ~I cannot find a declaration/installation of this in my installation of GAP.~ The declaration is part of the package `utils`: https://www.gap-system.org/Packages/utils.html which is not a dependency of `RingsForHomalg`. Thus, the tests of `RingsForHomalg` fail. This causes CI errors in `homalg_project` and `CAP`.

**Comment by mohamed-barakat** [comment]
My GAP 4.9.2 and plesken's 4.9.1 do have a `RandomCombination`. Is CircleCI using a newer version of GAP?

**Comment by zickgraf** [comment]
I found the definition, it's part of the package `utils`: https://www.gap-system.org/Packages/utils.html I will adapt the title of the issue.

**Comment by mohamed-barakat** [comment]
Thanks for investigating.
