### ISSUE TITLE
PrimitiveCollections( fan ) - extension of (N)Convex?

### ISSUE THREAD

**Issue by HereAround** [homalg-project/homalg_project#257]
The computation of the SR ideal of a toric variety requires to compute the so-called primitive collections of the associated fan (c.f. discussion in Cox-Little-Schenk after definition 5.5). That is why, the improved algorithm proposed in https://github.com/homalg-project/homalg_project/issues/244 computes these primitive collections.

In my opinion, it would be cleaner to add a method "PrimitiveCollections" to NConvex, which returns the primitive collections of a given fan.

I can provide a PR for this if @kamalsaleh you consider this a viable extension of NConvex.

**Comment by kamalsaleh** [comment]
Thanks you for suggesting this and of course you can provide a PR.

**Comment by HereAround** [comment]
Thanks @kamalsaleh - the proposed extension to NConvex is here: https://github.com/homalg-project/NConvex/pull/1

**Comment by mohamed-barakat** [comment]
What is the state of this issue?

**Comment by HereAround** [comment]
I think the suggested PRs have all been merged. Hence, I close this one.
