### ISSUE TITLE
Convex - tests fail and latex errors upon creation of documentation

### ISSUE THREAD

**Issue by HereAround** [homalg-project/homalg_project#259]
Building the documentation of Convex triggers LaTeX-errors of the following form:

! Illegal parameter number in definition of \reserved@a.
<to be read again> 

Also the tests for this package fail. Some with "no method found". I use the following commit of the homalg_project c11b040281fb5a8e7e10ffb6ea54906cc0975be8. These messages could in principle originate from outdated (external) software on my system. Hence, this needs to be verified.

However, there also seem to be changes due to altered display methods, e.g. 
P := Polytope( [ [ 2, 0 ], [ 0, 2 ], [ -1, -1 ] ] );
NFP := NormalFan( P );
C1 := MaximalCones( NFP )[ 1 ];
Expected output:
<A cone in |R^2>
But found:
<A pointed cone in |R^2>

Finally, results of computations have changed. For example

C := Cone([[1,2,3],[2,1,1],[1,0,0],[0,1,1]]);
IsSimplicial( C );
Expected output:
true
But found:
false

**Comment by mohamed-barakat** [comment]
We stopped supporting `PolymakeInterface` and `Convex` and they will not be deposited with GAP in the future. The part of their functionality we use in `ToricVarieties` is now covered by the deposited packages `NormalizeInterface`, `CddInterface`, and `NConvex`, the last two maintained by @kamalsaleh. Any future use of `polymake` will be through `Polymake.jl` which is a component of `Oscar`.

**Comment by mohamed-barakat** [comment]
> Also the tests for this package fail. Some with "no method found". I use the following commit of the homalg_project [c11b040](https://github.com/homalg-project/homalg_project/commit/c11b040281fb5a8e7e10ffb6ea54906cc0975be8). These messages could in principle originate from outdated (external) software on my system. Hence, this needs to be verified.
> 
> However, there also seem to be changes due to altered display methods, e.g.
> P := Polytope( [ [ 2, 0 ], [ 0, 2 ], [ -1, -1 ] ] );
> NFP := NormalFan( P );
> C1 := MaximalCones( NFP )[ 1 ];
> Expected output:
> <A cone in |R^2>
> But found:
> <A pointed cone in |R^2>
> 
> Finally, results of computations have changed. For example
> 
> C := Cone([[1,2,3],[2,1,1],[1,0,0],[0,1,1]]);
> IsSimplicial( C );
> Expected output:
> true
> But found:
> false

This now works as expected:

```gap
gap> P := Polytope( [ [ 2, 0 ], [ 0, 2 ], [ -1, -1 ] ] );
<A polytope in |R^2>
gap> NFP := NormalFan( P );
<A complete fan in |R^2>
gap> C1 := MaximalCones( NFP )[ 1 ];
<A cone in |R^2>
gap> C := Cone([[1,2,3],[2,1,1],[1,0,0],[0,1,1]]);
<A cone in |R^3>
gap> IsSimplicial( C );
true
```
