### ISSUE TITLE
Gauss::Rank() error.

### ISSUE THREAD

**Issue by SteveGoldstein** [homalg-project/homalg_project#264]
We are trying to use the Gauss package to compute the rank of a large number of sparse matrices for an algebraic geometry project, but we're encountering what looks like a bug, either in our code or in `Gauss::Rank()`.

For example, with this matrix:
    
[multidegree_4_7_28.dat](https://github.com/homalg-project/homalg_project/files/3278701/multidegree_4_7_28.dat.txt)

the code below returns 43 ( = number of rows) as the rank.  We have implemented two other methods for rank computations, one in Matlab using an LU factorization and one in MAGMA.  Both methods report the rank as 42.  We have confidence that the MAGMA and Matlab results are correct, based on the fact that this value is consistent in the context of the Betti tables we've constructed.

I've found several examples from our database in which `Gauss::Rank() `reports 
`rank = number of rows of the input matrix` 
when the MAGMA and Matlab LU methods report a smaller value.  We've tried to construct some smaller, simple examples of matrices with `rank < number of rows`;  in all of these `Gauss::Rank'`s value is correct.

Is there a bug in our code?  Or does this look like a bug in Gauss?

Thank you,
Steve Goldstein
University of Wisconsin-Madison

Code:
[ranks.rational.gap](https://github.com/homalg-project/homalg_project/files/3278696/ranks.rational.gap.txt)

FYI:  References to our project:
    https://www.tandfonline.com/doi/abs/10.1080/10586458.2018.1474506
    https://arxiv.org/abs/1905.1266 

Versions:  Gauss-2018.09.08;  GAP 4.10.1;
Platform:   `uname -a` 
`Linux greenbay 5.0.0-16-generic #17-Ubuntu SMP Wed May 15 10:52:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by alex-konovalov** [comment]
Thank you @SteveGoldstein. Just to add that I can reproduce the problem (as in your email to GAP Support today) using GAP 4.10.1 installation under macOS.

**Comment by fingolfin** [comment]
@SteveGoldstein I believe there is a bug in your code. To quote the documentation for `SparseMatrix`:
> indices must be a list of length nrows containing lists of the column indices of the matrix in ascending order.

But your code does not do this. If I replace the last loop by this, then I get the correct result:
```gap
for r in [1..maxR] do
    Add(cols, LookupDictionary(SMC,r));
    Add(vals, LookupDictionary(SMV,r));
    SortParallel(cols[Length(cols)], vals[Length(cols)]);
od;
```

CC @sebasguts @mohamed-barakat

**Comment by SteveGoldstein** [comment]
Thanks for finding the bug in my code!

**Comment by mohamed-barakat** [comment]
Thanks @SteveGoldstein for reporting and thanks @fingolfin for pointing out the mistake in the report, the lack of proper error handling, and the PR #265.
