### ISSUE TITLE
Remove outdated forks of various packages?

### ISSUE THREAD

**Issue by fingolfin** [homalg-project/homalg_project#274]
There are several outdate forks of packages in the homalg-project organization. Is this intentional? It occasional leads to confusing when people use these instead of the correct upstream repositories. At the very least, it would be nice if the repository descriptions could be changed to make it clear that these are forks and possibly outdated.

- https://github.com/homalg-project/AutoDoc
- https://github.com/homalg-project/NormalizInterface
- https://github.com/homalg-project/ferret
- https://github.com/homalg-project/SingularInterface

**Comment by mohamed-barakat** [comment]
I principle, these should be the versions that are tested with the homalg project, as I cannot yet guarantee that future versions work.

**Comment by fingolfin** [comment]
Fair enough. But that also means that you won't be testing with the versions shipped with GAP, which means that the next time you make releases of the homalg packages, it may turn out that they are broken by an update to some of your dependencies...

Anyway, as I already said, if you need to keep those works, then it would be good if at the very least, the repository description string for each could be changed to clearly state the purpose of this.

**Comment by mohamed-barakat** [comment]
I have now deleted all of them.
