### ISSUE TITLE
CI is currently failing

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/homalg_project#276]
Somehow the two original commits from https://github.com/homalg-project/homalg_project/pull/272 with failing CI are now on master. They should probably be reverted.

Edit: These are the commits:
0b932a2b3601a5b81fc1262db2f16633a72372be
d3421bfe3eaf62f5a61d642e6465fa3a65902c7b

**Comment by mohamed-barakat** [comment]
Thanks for reporting. I reset --hard and pushed again.
