### ISSUE TITLE
Checking if an element belongs to some ring may fail or raise error

### ISSUE THREAD

**Issue by kamalsaleh** [homalg-project/homalg_project#311]
```
LoadPackage( "RingsForHomalg" );
k := HomalgRingOfIntegers( );
One(k) in k;
# true
k := HomalgFieldOfRationalsInSingular(  ) * "x";
One(k) in k;
# true
k := HomalgRingOfIntegers( 5 );
One(k) in k;
# false
k := HomalgRingOfIntegers( ) / 5;
One(k) in k;
Error, no method found! 
RootOfDefiningPolynomial( F ) at /home
```

This may lead to unexpected behavior, for example as in https://github.com/homalg-project/CAP_project/blob/c2fb9b08f3836bed61f7d4dcf3c1be509006e46d/CAP/gap/MethodRecord.gi#L1197

**Comment by mohamed-barakat** [comment]
Ah, I should install in for residue class rings.

**Comment by kamalsaleh** [comment]
That would solve the issue in almost all instances, but using `HomalgRingOfIntegers(p)` still needs another solution, since it does not have the filter `IsHomalgResidueClassRingRep`
