### ISSUE TITLE
Error when creating an internal multivariate polynomial ring

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/homalg_project#325]
I try to create an internal multivariate polynomial ring as follows:
```
gap> LoadPackage("RingsForHomalg");;
gap> QQ := HomalgFieldOfRationals();;
gap> QQ * "x,y";
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `CreateHomalgTable' on 1 arguments at lib/methsel2.g:249 called from
CreateHomalgTable( r ) at homalg_project/MatricesForHomalg/gap/HomalgRing.gi:1665
```
Is this a bug, are internal multivariate polynomial rings unsupported, or am I doing something wrong?

Edit: additionally I get an error when trying to create a polynomial in an internal univariate polynomial ring:
```
gap> "x" / (QQ * "x");
Error, Could not evaluate string.
 at lib/string.gi:658 called from
EvalString( arg[1] ) at homalg_project/MatricesForHomalg/gap/HomalgRing.gi:2282
```
The same question I posed above applies.

Edit2:
Trying to create a univariate polynomial ring in an external GAP also gives an error:
```
gap> QQ := HomalgFieldOfRationalsInExternalGAP();;
gap>  QQ * "x";
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `IsUFDFamily' on 1 arguments at lib/methsel2.g:249 called from
IsUFDFamily( efam ) at lib/ratfun.gi:742 called from
RationalFunctionsFamily( ElementsFamily( FamilyObj( r ) ) ) at lib/ringpoly.gi:236 called from
PolynomialRing( R, ParseListOfIndeterminates( indets ) ) at homalg_project/MatricesForHomalg/gap/HomalgRing.gi:2029
```

**Comment by mohamed-barakat** [comment]
GAP internal multivariate polynomial rings are not supported as they won't be computable due to the lack of GB in GAP. Homalg rings have the commitment to be (two-sided) computable, i.e., their category of matrices has weak kernels/cokernels and lifts/colifts.

**Comment by zickgraf** [comment]
Ah, I see!

Do you have any thoughts regarding the errors in the univariate case? (I have edited the first comment, so it probably wasn't part of the notification email).

**Comment by mohamed-barakat** [comment]
The exercises of the computer course make the univariate polynomial ring over a constructive field computable. I still have the two files in a private branch and am waiting for some time where I have nothing else to do to add them to `MatricesForHomalg` :)

**Comment by zickgraf** [comment]
I understand, thanks :-)
