### ISSUE TITLE
Add 4ti2 binaries to the test suite and test package 4ti2Interface

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/homalg_project#328]
Kamal and I updated `4ti2Interface` and turned the existing example files into test files. For them to work 4ti2 has to be installed in the homalg test suite.

**Comment by zickgraf** [comment]
I have installed `4ti2` on homalgjenkins. If you want to have in available in CircleCI, you can add it to the apt command in `.circleci/config.yml`.

**Comment by mohamed-barakat** [comment]
Just `aptget 4ti2`?

**Comment by zickgraf** [comment]
It seems to be available in Ubuntu (https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=4ti2), so yes, adding it to the existing `apt install` command should suffice.

**Comment by mohamed-barakat** [comment]
Thank you very much, also for taking care of jenkins-ci.

**Comment by mohamed-barakat** [comment]
For the records: I will disable testing `PolymakeInterface` and `Convex`. We stopped supporting the two packages and they will not be deposited with `GAP` in the future. The part of their functionality we use in `ToricVarieties` is now covered by the deposited packages `NormalizeInterface`, `CddInterface`, and `NConvex`, the last two maintained by @kamalsaleh. Any future use of polymake will be through `Polymake.jl` which is a component of `Oscar`.
