### ISSUE TITLE
Create ConvertRow/ColumnToMatrix & ConvertMatrixToRow/Column

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/homalg_project#331]
After issue #330 has been resolved I will create

* `ConvertRowToMatrix`
* `ConvertMatrixToRow`
* `ConvertColumnToMatrix`
* `ConvertMatrixToColumn`

with the following behavior
```
gap> row := HomalgMatrix( [1,2,3,4,5,6], 1, 6, HomalgRingOfIntegers());
<A 1 x 6 matrix over an internal ring>
gap> Display( ConvertRowToMatrix( row, 2, 3 ) );
[ [  1,  2,  3 ],
  [  4,  5,  6 ] ]
gap> ConvertMatrixToRow( ConvertRowToMatrix( row, 2, 3 ) ) = row;
true
gap> col := HomalgMatrix( [1,2,3,4,5,6], 6, 1, HomalgRingOfIntegers());
<A 6 x 1 matrix over an internal ring>
gap> Display( ConvertColumnToMatrix( col, 3, 2 ) );
[ [  1,  4 ],
  [  2,  5 ],
  [  3,  6 ] ]
gap> ConvertMatrixToColumn( ConvertColumnToMatrix( col, 3, 2 ) ) = col;
true
```

This should overcome two serious bottlenecks in `LinearAlgebraForCAP` regarding the methods for
* `InterpretMorphismAsMorphismFromDistinguishedObjectToHomomorphismStructure`
* `InterpretMorphismFromDistinguishedObjectToHomomorphismStructureAsMorphism`

@kamalsaleh: Merging commit ab1dc53 breaks `BBGG` and `DerivedCategories` and you need to comply with the new naming conventions described in #330. You might also be interested in the upcoming four new operations above which will be introduced soon.

**Comment by sebastianpos** [comment]
I would be glad if that functionality could then also be used for the category of rows/columns in `FreydCategoriesForCAP`. Note that Rows/Cols knows that it is abelian if the underlying ring is a field, and in this sense, it should replace `LinearAlgebraForCAP.`
