### ISSUE TITLE
4ti2Interface (2020.05.11) - bug on Plesken

### ISSUE THREAD

**Issue by HereAround** [homalg-project/homalg_project#335]
On plesken, the following lines of code:

```gap
LoadPackage( "4ti2I" );
l := [ [ 0, -1, 0, -1 ], [ 0, -2, 1, 0 ], [ 1, 2, 0, 0 ] ];
p := [ 2, 4, -3 ]
4ti2Interface_zsolve_equalities_and_inequalities_in_positive_orthant( l, p, [], [] );
```

lead to

```gap
Error, this file /tmp/tmRpIYKR/gap_4ti2_zsolve.zfree does not exist, it should have been created by 4ti2
```

The tests for 4ti2Interface succeed.

**Comment by kamalsaleh** [comment]
Just in case you don't know, the commands `NConvex:SolveEqualitiesAndInequalitiesOverIntergers` and `4ti2Interface:4ti2Interface_zsolve_equalities_and_inequalities` do the same thing. If you want only positive solutions you can add extra argument to declare which variable(s) you want to be positive. So, you can do the following:
```
LoadPackage( "NConvex" );
l := [ [ 0, -1, 0, -1 ], [ 0, -2, 1, 0 ], [ 1, 2, 0, 0 ] ];
p := [ 2, 4, -3 ];
SolveEqualitiesAndInequalitiesOverIntergers( l, p, [], [] );  # to get all sols
[ [ [ 1, -2, 0, 0 ] ], [  ], [ [ 2, -1, -2, 1 ] ] ]
SolveEqualitiesAndInequalitiesOverIntergers( l, p, [], [], [ 1, 1, 1, 1 ] );  # to get positive sols
[ [  ], [  ], [  ] ]
```

**Comment by HereAround** [comment]
Thank you Kamal. That is a good idea.

The above example happens in a computation in SheafCohomologies (which is not yet detected by one of my tests...). By following your suggestion, I will consider to change my 4ti2-calls into calls to NConvex. I will report on this.

Anyways, I guess there is some interest in figuring out why 4ti2Interface fails for the above.

**Comment by kamalsaleh** [comment]
My first thought is the following, it seems that `4ti2Interface` is trying to extract the free part of the solution which should actually be ignored when we compute only the positive solutions. So, I think 4ti2 is doing fine, and 4ti2Interface should just don't ask for the free part if the sign vector contains only 1's.

**Comment by mohamed-barakat** [comment]
Originally: When `4ti2Interface` did not find the file it returned an empty list. Would this be the correct answer in this case?

I thought that simply returning an empty list upon a missing file is very dangerous and I now raise the error you see above. The previous behavior also returned empty lists, whenever the `4ti2` binaries are broken for unfulfilled dependencies.

**Comment by kamalsaleh** [comment]
Yes, an empty list would be the correct answer in this case.

**Comment by kamalsaleh** [comment]
> I will consider to change my 4ti2-calls into calls to NConvex. I will report on this.

I think it would be better to have `if statement` instead of removing the 4ti2 calls. In that case you can always switch between them according to which operation is faster.
