### ISSUE TITLE
file /tmp/.../gap_4ti2_zsolve.zfree does not exist

### ISSUE THREAD

**Issue by HereAround** [homalg-project/homalg_project#345]
```
LoadPackage( "4ti2Interface");
4ti2Interface_zsolve_equalities_and_inequalities( [ [ 1 ] ], [ 1 ], [ [ 1 ] ], [ 0 ] );
```

This leads to the above error, however the result should be ```[ [ [ 1 ] ], [  ], [  ] ]```.

Potentially, this is related to https://github.com/homalg-project/homalg_project/issues/335.

**Comment by kamalsaleh** [comment]
By many experiments, it seems that 4ti2 creates a file for the free part only if it is non-trivial. In that case, I think the fix would be to check for the existence of the file, then in affirmative case read it.

**Comment by kamalsaleh** [comment]
https://4ti2.github.io/
```
 * When the cone is not pointed, "hilbert" now outputs a "zfree" file,
   containing a lattice basis, in addition to the "hil" file.  

```
