### ISSUE TITLE
Problem with LaTeXString

### ISSUE THREAD

**Issue by alex-konovalov** [homalg-project/homalg_project#349]
It is also defined in RCWA package, and now the new MatricesForHomalg breaks package loading:

```
#I  RCWA: start reading file 'init.g'
Error, operation `LaTeXString' has been declared as a one argument Operation and cannot also be an Attribute at /circa/scratch/gap-jenkins/workspace/GAP-pkg-update-stable-quicktest/GAPCO\
PTS/64build/GAPGMP/gmp/GAPTARGET/packagesload/label/kovacs/GAP-pkg-update-stab\
le-snapshot/lib/oper.g:1294 called from
```

Indeed,

```
brk> ShowDeclarationsOfOperation(LaTeXString);
Available declarations for operation <Operation "LaTeXString">:
  1: /Users/alexk/GITREPS/gap/pkg/MatricesForHomalg-2020.09.02/gap/HomalgRing.gd:1721 with 1 arguments, and filters [ IsHomalgRingElement ]
  2: /Users/alexk/GITREPS/gap/pkg/MatricesForHomalg-2020.09.02/gap/HomalgMatrix.gd:1275 with 1 arguments, and filters [ IsHomalgMatrix ]
```

Could you please define it as an attribute and check that RCWA can be loaded after that? A new release will be appreciated, since this now breaks Jenkins tests.

**Comment by mohamed-barakat** [comment]
I do not like the idea of an attribute as we are using `LaTeXString` for view methods in `Julia` and my view method depends on the knowledge status of the object, hence an operation and not an attribute.

**Comment by fingolfin** [comment]
I agree with Mohamed's reasoning here; perhaps RCWA should be changed to make it an operation, not an attribute? (I mean, does one really need to cache the output of `LaTeXString`? The only times this would matter, it seems to me, is when a single complex object is printed this way many *many* times, which seems rather unusual?

**Comment by fingolfin** [comment]
Put another way: String, ViewString etc. are not attributes either, for similar reasons.

**Comment by zickgraf** [comment]
> String, ViewString etc. are not attributes either, for similar reasons.

At least in GAP 4.11, `String` seems to be an attribute. We are using this [here](https://github.com/homalg-project/InternalModules/blob/4d0a473e8ac4bee787d6a883fc5d7bbec5f000c1/gap/Tools.gi#L14) to allow the user to actively set a string for certain objects. A similar application might exist for `LaTeXString`, for example if I want to force a character to be displayed as `\chi` in LaTeX. So maybe it makes sense to keep both version?
