### ISSUE TITLE
LaTeXStrings for homalg rings

### ISSUE THREAD

**Issue by kamalsaleh** [homalg-project/homalg_project#351]
This issue is a reminder. Since we started using `LaTeXStringOp` for elements and matrices, it would also be nice to do the same for rings, and to be able to assign such strings to complicated rings. That can lead to better outputs for objects and morphisms in various categories that are based on homalg rings.

**Comment by mohamed-barakat** [comment]
Thank you very much. Yes, we can work on this gradually

**Comment by kamalsaleh** [comment]
I think this reminder-issue can be closed since we have started adding such methods, for example in https://github.com/homalg-project/homalg_project/pull/380
