### ISSUE TITLE
Slideshow in the README has outdated links

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/homalg_project#356]
The title and subtitle of the first page of the slideshow in the README link to https://homalg.math.rwth-aachen.de/ which does not exist.

**Comment by mohamed-barakat** [comment]
Thanks for spotting it :)

**Comment by zickgraf** [comment]
The link to the authors is still broken: https://github.com/homalg-project/homalg_project/index.php/homalg-project-authors
