### ISSUE TITLE
Automated releases

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/homalg_project#361]
I have managed to get the release-gap-package script running inside the CI, see https://github.com/zickgraf/FinSetsForCAP/runs/1220602873?check_suite_focus=true That is, we can now make automated releases, if we want to :-) There are two caveats however:

1. When making automated releases, one must not push to master too frequently (i.e., while the CI is still running). Otherwise we get race conditions.
2. We would need to make the following changes to `make_dist_for_homalg.sh`:
      1. Remove `--no-push`.
      2. Remove the step copying the `package.yml`s. Instead, symlink the files.
      3. Remove the step copying `homalg-project.pdf` and remove `homalg-project.pdf` from the `gh-pages` branch. Instead, move it to https://homalg-project.github.io/ or update all links to  use https://raw.githubusercontent.com/homalg-project/homalg_project/master/images/homalg-project.pdf.

Are you interested in this? If yes, I can provide PRs for 2.i. and 2.ii., but would need help for 2.iii.

**Comment by mohamed-barakat** [comment]
> I have managed to get the release-gap-package script running inside the CI, see https://github.com/zickgraf/FinSetsForCAP/runs/1220602873?check_suite_focus=true

In which CI? Jenkins? I was unable to find it neither in the yaml files of circle-ci nor of GitHub actions.

> That is, we can now make automated releases, if we want to :-)

Excellent. A release process works then by pushing a tag to the master branch?

> There are two caveats however:
> 
> 1. When making automated releases, one must not push to master too frequently (i.e., while the CI is still running). Otherwise we get race conditions.

I see. For this convenience, we can modify our workflow?

> 2. We would need to make the following changes to `make_dist_for_homalg.sh`:
>    
>    1. Remove `--no-push`.

Yes.

>    2. Remove the step copying the `package.yml`s. Instead, symlink the files.

Yes.

>    3. Remove the step copying `homalg-project.pdf` and remove `homalg-project.pdf` from the `gh-pages` branch. Instead, move it to https://homalg-project.github.io/ or update all links to  use https://raw.githubusercontent.com/homalg-project/homalg_project/master/images/homalg-project.pdf.

It is no problem to host the file on https://homalg-project.github.io/.

> Are you interested in this? If yes, I can provide PRs for 2.i. and 2.ii., but would need help for 2.iii.

I am very much interested :) Excellent work.

**Comment by zickgraf** [comment]
> In which CI? Jenkins? I was unable to find it neither in the yaml files of circle-ci nor of GitHub actions.

In GitHub Actions: https://github.com/zickgraf/FinSetsForCAP/commit/dd12ce81db4901a467a594114b87310bb54c18e6#diff-668d39c06df266501b012cc9e746e343

> Excellent. A release process works then by pushing a tag to the master branch?

No, it simply runs the release script on every commit to master, that is, it makes a release every time a PackageInfo.g file with a newer version is pushed.

I will provide a PR :-)

**Comment by mohamed-barakat** [comment]
>    3. Remove the step copying `homalg-project.pdf` and remove `homalg-project.pdf` from the `gh-pages` branch. Instead, move it to https://homalg-project.github.io/ or update all links to  use https://raw.githubusercontent.com/homalg-project/homalg_project/master/images/homalg-project.pdf.

This slideshow is now under https://homalg-project.github.io/docs/homalg_project/homalg_project.pdf

**Comment by zickgraf** [comment]
Fixed by:

https://github.com/homalg-project/homalg_project/commit/188a28c22eb5e4279e695c43092668cd3fc4de8f
https://github.com/homalg-project/homalg_project/commit/6b4c68cb7d35b9331d32a81609d9407cacfeaa89
https://github.com/homalg-project/homalg_project/commit/871a7e41a089a4ad9b4315bdb45dedd8831f10f7
