### ISSUE TITLE
Problems with RowEchelonForm

### ISSUE THREAD

**Issue by alex-konovalov** [homalg-project/homalg_project#438]
Please see https://github.com/gap-packages/cryst/issues/24 - I confirm that this still happens with all homalg lost recent releases as of this morning (what I have picked up is at https://github.com/gap-system/gap/wiki/Package-updates-status). This was observed already for a while - sorry, had no time to investigate it during term-time. Maybe the best way to resolve is to update Cryst though.

**Comment by mohamed-barakat** [comment]
Would it make sense to make a PR to gap-packages/cryst?

**Comment by alex-konovalov** [comment]
I think so!

**Comment by alex-konovalov** [comment]
but it still uses travis, better to switch it to GitHub actions first!

**Comment by alex-konovalov** [comment]
@mohamed-barakat I've made https://github.com/gap-packages/cryst/pull/25 to switch it to GitHub actions.

**Comment by alex-konovalov** [comment]
Nice, it seems like next Cryst release is coming very soon: https://github.com/gap-packages/cryst/commit/29656aa1a2676cdccd57585e781d5b07a4677c0a
