### ISSUE TITLE
Bug in `ReducedSyzygiesGeneratorsOfRows` over `R = ZZ[a,b]` using Singular

### ISSUE THREAD

**Issue by kamalsaleh** [homalg-project/homalg_project#441]
The instance is attached to this file: [kernellift.txt](https://github.com/homalg-project/CAP_project/files/6616115/kernellift.txt).
This is a reduction of the another error which occurs while computing a homology of a complex reported by Leonardo Maltoni (a student of @djuteau).

**Comment by mohamed-barakat** [comment]
I have transferred the issue to homalg_project :)

**Comment by mohamed-barakat** [comment]
It seems as if Singular `nres` is buggy for ZZ. If I remember correctly, I have already reported two bugs related to nres years ago.

**Comment by kamalsaleh** [comment]
Exactly, for example here https://github.com/homalg-project/homalg_project/issues/370.

**Comment by mohamed-barakat** [comment]
With

```
...
RP := homalgTable( R );

Unbind( RP!.ReducedSyzygiesGeneratorsOfRows );
Unbind( RP!.ReducedSyzygiesGeneratorsOfColumns );
...
```
it works. So it is either a bug in `nres` or homalg is using `nres` in a wrong way.
