### ISSUE TITLE
Syntax error when trying to load ToolsForHomalg

### ISSUE THREAD

**Issue by djuteau** [homalg-project/homalg_project#461]
Dear homalg team,

 I tried to install cap and homalg on my new laptop, but I got the error below. "Last" is not defined (in ToolsForHomalg). Was it modified recently?

Thanks!
Daniel

Loading  ToolsForHomalg 2022.01-01 (Provides special methods and knowledge propagation tools)
by Mohamed Barakat (https://mohamed-barakat.github.io),
   Sebastian Gutsche (https://sebasguts.github.io), and
   Markus Lange-Hegermann (http://wwwb.math.rwth-aachen.de/~markus/).
Homepage: https://homalg-project.github.io/pkg/ToolsForHomalg
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Syntax warning: Unbound global variable in /home/daniel/.gap/pkg/CAP_project/CAP/gap/ToolsForCategories.gi:895
    method := Last( args );
                  ^
Syntax warning: Unbound global variable in /home/daniel/.gap/pkg/CAP_project/CAP/gap/ToolsForCategories.gi:925
    method := Last( args );
                  ^
Syntax warning: Unbound global variable in /home/daniel/.gap/pkg/CAP_project/CAP/gap/MethodRecord.gi:4755
                given_source_argument_name := Last( record.(with_given_name).input_arguments_names );
                                                  ^
Syntax warning: Unbound global variable in /home/daniel/.gap/pkg/CAP_project/CAP/gap/MethodRecord.gi:4759
                given_range_argument_name := Last( record.(with_given_name).input_arguments_names );
                                                 ^
Syntax warning: Unbound global variable in /home/daniel/.gap/pkg/CAP_project/CAP/gap/MethodRecord.gi:4764
                given_range_argument_name := Last( record.(with_given_name).input_arguments_names );
                                                 ^
Error, Variable: 'Last' must have an assigned value in
  given_source_argument_name := Last( record.(with_given_name).input_arguments_names ); at /home/daniel/.gap/pkg/CAP_project/CAP/gap/MethodRecord.gi:4755 called from 
<function "CAP_INTERNAL_ENHANCE_NAME_RECORD">( <arguments> )
 called from read-eval loop at /home/daniel/.gap/pkg/CAP_project/CAP/gap/MethodRecord.gi:4982
you can 'return;' after assigning a value

**Comment by zickgraf** [comment]
What version of GAP are you using? `Last` is a GAP function which is available since GAP 4.11. We should probably bump the GAP dependency (probably for all our packages, since we are not running tests with GAP < 4.11, so many things might be broken).

**Comment by zickgraf** [comment]
> So I shouldn't use apt to have the latest release of GAP?

In general: no, you shouldn't. The GAP versions in the Ubuntu or Debian repos are usually fixed at the version when the respective version of Ubuntu or Debian was released, which can be more than two years in the past.

You can either update to Ubuntu 21.10 or Debian 11, use our packages via Julia (https://homalg-project.github.io/docs/installation) or compile GAP yourself (https://www.gap-system.org/Download/install.html).

**Comment by mohamed-barakat** [comment]
`ToolsForHomalg` loads successfully. The problem is that `CAP` uses the command `Last` which was probably introduced in `GAP 4.11` without raising the dependency accordingly.

**Comment by djuteau** [comment]
Yes, exactly! Thank you both, Fabian and Mohamed!

**Comment by zickgraf** [comment]
Thanks for notifying us, we will now bump the GAP dependency automatically in the issue linked above :-)
