### ISSUE TITLE
Add `TestFile` entries to PackageInfo records?

### ISSUE THREAD

**Issue by fingolfin** [homalg-project/homalg_project#465]
Right now the packages in this repository all lack a `TestFile` entry. That means that we cannot perform any CI tests with them when compiling the package distribution. That means we won't notice when we e.g. import a package update that break homalg packages, or make a change to GAP that does so, etc.

Thus I think it'd be useful for you if such a field was added in each package. Perhaps it could point to the respective `maketest.g` file, although to be useful, they'd have to be slightly modified: the script pointed at by `TestFile` should either be a `.tst` file, or else it should be a GAP file that at the end exits GAP, with an exit code indicating whether tests were successful or not. Say:
```gap
if success then
    FORCE_QUIT_GAP(0);
else
    FORCE_QUIT_GAP(1);
fi;
```

**Comment by zickgraf** [comment]
@mohamed-barakat Getting rid of the `maketest.g` files (which do not provide a proper exit code) and replacing them by `tst/testall.g` can be done by removing `docu_only` in the entries of the packages in PackageJanitor (see https://github.com/homalg-project/PackageJanitor/commit/b6ed734efb488be635dd3582e2d09e054eb3849d for an example). On a technical level this is easy, but decisions have to be made (e.g. as in #398). That's why I did/do not pursue this further.

If all packages use `tst/testall.g`, I can easily enhance `PackageJanitor` to set `TestFile` correctly.

**Comment by fingolfin** [comment]
Note that it is not necessary to rename those files, `TestFile` can contain any filename relative to the package root.

**Comment by fingolfin** [comment]
I see that some (more) homalg packages now `TestFile` entries. Unfortunately, there are problems:
- `cap`: test tries to load a package `HomologicalAlgebraForCAP` which is however not deposited (see e.g. [this log](https://github.com/fingolfin/PackageDistro/runs/5528180272?check_suite_focus=true)).
- `generalizedmorphismsforcap` (and a few others): I get
  ```
  LoadPackage( "LinearAlgebraForCAP", false );
  # Expected output:
  true
  # But found:
  Syntax warning: Unbound global variable in /home/runner/gap/pkg/MatricesForHomalg-2022.03-01/gap/Tools.gi:4563
      return Random( R, RandomCombination( [ 0 .. 10 ], Random( [ 1 .. 11 ] ) ) );
                        ^^^^^^^^^^^^^^^^^
  true
  ```

**Comment by fingolfin** [comment]
Can't this student just install `utils`? Or rather, have them install `PackageManager` and then just use that to install all required packages?

**Comment by zickgraf** [comment]
> I see that some (more) homalg packages now `TestFile` entries.

Yes, all packages in `CAP_project` are now properly tracked by `PackageJanitor` :-)

>     * `cap`: test tries to load a package `HomologicalAlgebraForCAP` which is however not deposited (see e.g. [this log](https://github.com/fingolfin/PackageDistro/runs/5528180272?check_suite_focus=true)).

I have proposed a fix in https://github.com/homalg-project/CAP_project/pull/862.

**Comment by fingolfin** [comment]
Much better!

Still have one issue with ModulePresentationsForCAP-2022.03-02, although I guess one can argue about it: [this test run failed](https://github.com/fingolfin/PackageDistro/runs/5563590368?check_suite_focus=true) because of a missing Singular. Why is Singular missing? Because we only install it if a package is used that is known to need it. Here, "a package is used" means: "it is a dependency, direct or indirected, needed or suggested, of the package being tested".

For Homalg, I've determined `RingsForHomalg` is the package pulling in Singular (let me know if this is wrong or if other packages also pull it in).

Anyway, the failure seems to be due to a test `examples/Annihilator.g` in `ModulePresentationsForCAP` which uses `LoadPackage("RingsForHomalg")` and subsequently uses Singular. Yet `RingsForHomalg` is not a dependency (as defined above) for `ModulePresentationsForCAP`.

I see two ways to resolve this:
1. you add `RingsForHomalg` as a `SuggestedDependency` for `ModulePresentationsForCAP`  (assuming this makes sense for you)
2. I modify our scripts to declare that `ModulePresentationsForCAP ` requires `Singular` to be present (which is a bit of a hack, but I don't mind *shrug*)

**Comment by zickgraf** [comment]
> For Homalg, I've determined `RingsForHomalg` is the package pulling in Singular (let me know if this is wrong or if other packages also pull it in).

`RingsForHomalg` is definitely pulling Singular, for other packages @mohamed-barakat has to comment.

> Anyway, the failure seems to be due to a test `examples/Annihilator.g` in `ModulePresentationsForCAP` which uses `LoadPackage("RingsForHomalg")` and subsequently uses Singular. Yet `RingsForHomalg` is not a dependency (as defined above) for `ModulePresentationsForCAP`.
> 
> I see two ways to resolve this:
> 
>     1. you add `RingsForHomalg` as a `SuggestedDependency` for `ModulePresentationsForCAP`  (assuming this makes sense for you)
> 
>     2. I modify our scripts to declare that `ModulePresentationsForCAP ` requires `Singular` to be present (which is a bit of a hack, but I don't mind _shrug_)

Adding it as a suggested dependency sounds sensible to me. @mohamed-barakat?

I have noticed that `LinearAlgebraForCAP` is also still failing due to `FreydCategoriesForCAP` not being available. I will modify the failing test to not run in this case.

**Comment by fingolfin** [comment]
Thank you, @zickgraf, much appreciated

**Comment by zickgraf** [comment]
The issues with `LinearAlgebraForCAP` should (hopefully) now be fixed (https://github.com/homalg-project/CAP_project/pull/863).
