### ISSUE TITLE
Most of the new TestFile produce failures

### ISSUE THREAD

**Issue by fingolfin** [homalg-project/homalg_project#487]
See https://github.com/gap-system/PackageDistro/pulls for a list with non-merged PRs for homalg packages (ignore the two CAP related ones at the bottom, that's probably just a case of "need to be merged together"

I have not looked at all failures yet, but many seem to involve an error like this:
```
Error, Cannot include file doc/IO_ForHomalg.xml.
```

**Comment by fingolfin** [comment]
Several ways to fix this:
- bundle those generated .xml files with the release tarball (no harm in that, I think?). With ReleaseTools that'd be done anyway
- run `makedoc.g` as part of `maketest.g` to ensure these files are present
- don't extract the tests each time `maketest.g` is run, instead extract them once and the bundle the extracted test files inside the release tarball (a bunch of packages do it that way, esp. those which use the `extract_examples` AutoDoc feature

**Comment by fingolfin** [comment]
Note that right now I manually blocked all Homalg packages from updating in https://github.com/gap-system/PackageDistro/pulls to prevent excessive re-running of the CI tests there (~250 jobs times 12 packages equals 3000 jobs which would be re-run each time the package distro is updated -- I'd rather not do that :-).

Hence if you have fixed this (be it by disabling the `TestFile` statements or by fixing the test files), make sure to notify me so that I can unblock them.

**Comment by fingolfin** [comment]
@mohamed-barakat if this is resolved with the next few hours by new releases of the affected packages, then those new versions can still make it into 4.12.0. Otherwise, I'll use whatever is in the distro right now (what that means can be checked by inspecting the various PRs, e.g. https://github.com/gap-system/PackageDistro/pull/493/files shows that Gauss is currently at 2022.03-01 in the distro)

**Comment by mohamed-barakat** [comment]
I followed @zickgraf's suggestion in #488
* `ToolsForHomalg`
* `MatricesForHomalg`
* `GradedRingForHomalg`

If they do I can adapt the rest accordingly.

**Comment by fingolfin** [comment]
Tools and Graded already passed the test before. I'll look at matrices now

**Comment by mohamed-barakat** [comment]
> Tools and Graded already passed the test before. I'll look at matrices now

`4ti2Interface` should be also ready by now. I will do the rest in one go.

**Comment by fingolfin** [comment]
MatricesForHomalg passed in https://github.com/gap-system/PackageDistro/pull/486 :-)

**Comment by mohamed-barakat** [comment]
The rest will follow today.

**Comment by mohamed-barakat** [comment]
All packages except `LocalizeRingForHomalg` & `GradedModules` are now released. The two remaining ones will be hopefully released within the next hour (see https://github.com/homalg-project/homalg_project/pull/500).

**Comment by mohamed-barakat** [comment]
PR #500 will close this issue. If you still encounter failures it can be reopened.

**Comment by fingolfin** [comment]
PR #500 only deal with two packages. But also io_forhomalg, localizeringforhomalg, sco, examplesforhomalg, ringsforhomalg are affected.

**Comment by mohamed-barakat** [comment]
The others were dealt with in previous PRs. This was just the last one.

**Comment by mohamed-barakat** [comment]
You probably mean that the mentioned packages still fail your tests?

**Comment by fingolfin** [comment]
I can't confirm this, at least not for `IO_ForHomalg` and `HomalgToCAS` which did not receive any further updates since their 2022.08-01 release. But I will recheck the others.

**Comment by fingolfin** [comment]
No, I did not re-run tests for these packages yet. But I will for those which received an updated today (which I just somehow missed). Which leaves `IO_ForHomalg` and `HomalgToCAS`

**Comment by mohamed-barakat** [comment]
Oh, I forgot to bump the versions. I now bumped the versions of three updated but forgotten packages:
* `GradedRingForHomalg`
* `HomalgToCAS`
* `IO_ForHomalg`

They will be released once the tests pass. Sorry for the delay.

**Comment by fingolfin** [comment]
The tests for `RingsForHomalg` unfortunately fail because they require Magma (and a lot more) to be installed. But I can't do that in GitHub CI, obviously. Ideally, the tests for Magma/Sage/... would only be run if the respective CAS is actually available?

**Comment by fingolfin** [comment]
Good news: all updates are merged now, with the exception of `RingsForHomalg` (but I see @zickgraf is working on that, thanks!)

**Comment by zickgraf** [comment]
RingsForHomalg 2022.08-03 and IO_ForHomalg 2022.08-03 are released, so `RingsForHomalg` should now also succeed :-)

**Comment by fingolfin** [comment]
All good now. Thanks a lot for your efforts!

**Comment by mohamed-barakat** [comment]
Thank you for your patience and for the intensive testing.
