### ISSUE TITLE
(Another) small bug in gauss

### ISSUE THREAD

**Issue by ChrisJefferson** [homalg-project/homalg_project#562]
I decided to take a while look over `SYMMETRIC_DIFFERENCE_OF_ORDERED_SETS_OF_SMALL_INTEGERS`, and noticed another issue.

Statements like: `m := SparseMatrix( 1, 1, [[1..100]]); m+m+m;` lead to a crash, as `[1..100]` is a range, but `SDOOSOSI` calls `LEN_PLIST` right at the start, which doesn't work on ranges.

The easiest fix for this is to call `PLAIN_LIST(a); PLAIN_LIST(b);` at the start of the function. `PLAIN_LIST` will produce an error if it's input can't be turned into a plain list, and if it can be, then the rest of the function behaves correctly.

**Comment by mohamed-barakat** [comment]
I don't really understand what to do. I would be happy about a PR 😄

**Comment by ChrisJefferson** [comment]
In #566 :) Obviously, I imagine this might not get handled / merged for a while. Merry Christmas!

PS I think this code could do with some other testing, (for example) you can specify locations which are not in the matrix. However, that's an issue that should be handled in GAP, not the C part, so I'll leave it for someone else :)

**Comment by mohamed-barakat** [comment]
Thank you very much, Chris. Should we leave this issue open?

**Comment by ChrisJefferson** [comment]
I think all these issues are fixed now. It might be a good project (maybe for a student?) to write more tests, and try pushing functions, but there are (as far as I can tell) no more kernel-level crashes.

**Comment by mohamed-barakat** [comment]
Wonderful, then I will close the issue.

**Comment by mohamed-barakat** [comment]
Resolved with #566.
