### ISSUE TITLE
Switching UnderlyingObject to an attribute breaks LoadAllPackages

### ISSUE THREAD

**Issue by ChrisJefferson** [homalg-project/homalg_project#564]
PR #563 broke loading both fining and homalg, as fining also uses the name `UnderlyingObject` but makes it an operation. In the short term, it would be good to switch it back, so GAP's package loading works; there may be better longer-term plans. @fingolfin may have other opinions.

**Comment by fingolfin** [comment]
My bad, I should not have merged https://github.com/gap-system/PackageDistro/pull/675 and will now revert it.

**Comment by zickgraf** [comment]
Reverted in https://github.com/homalg-project/homalg_project/pull/565 and released: https://github.com/homalg-project/homalg_project/releases/tag/homalg-2022.12-02

Does it make sense to discuss turning `UnderlyingObject` into an attribute with FinInG, or do you expect "large" implications there?

**Comment by fingolfin** [comment]
I am de-facto maintainer of FinInG. I don't think there'll be a serious obstacle, but I did not really try. Would be worth to just submit a PR, though; if the CI pass, I'd be happy to merge it and make a release.

**Comment by zickgraf** [comment]
This is now properly fixed in FinInG and homalg.
