### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by sebasguts** [homalg-project/homalg_project#76]
<a href="https://github.com/sebastianpos"><img src="https://avatars.githubusercontent.com/u/2869916?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sebastianpos](https://github.com/sebastianpos)**
_Monday Oct 28, 2013 at 13:20 GMT_
_Originally opened as https://github.com/homalg-project/ToricVarieties/issues/3_

---

CombinatoricalRep -> CombinatorialRep

**Comment by fingolfin** [comment]
I think you guys resolve this already
