### ISSUE TITLE
Two bugfixes

### ISSUE THREAD

**Issue by sebasguts** [homalg-project/homalg_project#88]
<a href="https://github.com/sebasguts"><img src="https://avatars.githubusercontent.com/u/1068084?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sebasguts](https://github.com/sebasguts)**
_Wednesday Apr 02, 2014 at 13:44 GMT_
_Originally opened as https://github.com/homalg-project/Gauss/pull/11_

---

---

_**[sebasguts](https://github.com/sebasguts)** included the following code: https://github.com/homalg-project/Gauss/pull/11/commits_

**Comment by fingolfin** [comment]
Considering that the links included here do not work anymore, there seems no point in leaving this open? @mohamed-barakat ?

**Comment by mohamed-barakat** [comment]
You are right. I seem to have forgotten that the content of the issue was not migrated by @sebasguts and at some moment we decided to delete the old repositories.
